/**
 * Additional ONE FC business-domain semantic definitions.
 * Raw definitions only; semanticDataCatalog.js applies defaults/freezes them.
 *
 * No natural-language synonym lists belong here.
 */
export const AI_SEMANTIC_BUSINESS_FIELDS_RAW = [
  // customer_consultations
  { key:'consultation.id', label:'상담 내부 ID', description:'고객 상담 레코드의 내부 ID.', valueType:'integer', storage:{table:'customer_consultations',column:'id'}, systemManaged:true, privacyLevel:'internal' },
  { key:'consultation.customerId', label:'상담 고객 ID', description:'상담이 연결된 고객 ID.', valueType:'integer', storage:{table:'customer_consultations',column:'customer_id'}, systemManaged:true, privacyLevel:'internal' },
  { key:'consultation.userId', label:'상담 작성 사용자', description:'상담 레코드 소유/작성 사용자 ID.', valueType:'string', storage:{table:'customer_consultations',column:'user_id'}, systemManaged:true, privacyLevel:'internal' },
  { key:'consultation.gaId', label:'상담 GA', description:'상담 데이터의 GA 조직 ID.', valueType:'integer', storage:{table:'customer_consultations',column:'ga_id'}, systemManaged:true, privacyLevel:'internal' },
  { key:'consultation.body', label:'상담 내용', description:'고객 상담에서 작성한 본문 내용.', valueType:'string', storage:{table:'customer_consultations',column:'body'}, capabilities:{read:true,input:true,update:true} },
  { key:'consultation.date', label:'상담일', description:'실제 상담이 이루어진 날짜.', valueType:'date', storage:{table:'customer_consultations',column:'consultation_date'}, capabilities:{read:true,input:true,update:true} },
  { key:'consultation.contactResult', label:'연락 결과', description:'상담/연락 시도 결과.', valueType:'string', storage:{table:'customer_consultations',column:'contact_result'}, capabilities:{read:true,input:true,update:true} },
  { key:'consultation.followUpStatus', label:'후속관리 상태', description:'상담 후 후속 연락 진행 상태.', valueType:'string', storage:{table:'customer_consultations',column:'follow_up_status'}, capabilities:{read:true,input:true,update:true} },
  { key:'consultation.nextContactDate', label:'다음 연락일', description:'고객에게 다시 연락할 예정 날짜.', valueType:'date', storage:{table:'customer_consultations',column:'next_contact_date'}, capabilities:{read:true,input:true,update:true} },
  { key:'consultation.followUpNote', label:'후속관리 메모', description:'다음 연락 또는 후속관리와 관련된 메모.', valueType:'string', storage:{table:'customer_consultations',column:'follow_up_note'}, capabilities:{read:true,input:true,update:true} },
  { key:'consultation.createdAt', label:'상담 등록일', description:'상담 레코드 생성 시각.', valueType:'datetime', storage:{table:'customer_consultations',column:'created_at'}, systemManaged:true, privacyLevel:'internal' },
  { key:'consultation.updatedAt', label:'상담 수정일', description:'상담 레코드 마지막 수정 시각.', valueType:'datetime', storage:{table:'customer_consultations',column:'updated_at'}, systemManaged:true, privacyLevel:'internal' },

  // todos
  { key:'todo.id', label:'할일 내부 ID', description:'할일 레코드 내부 ID.', valueType:'integer', storage:{table:'todos',column:'id'}, systemManaged:true, privacyLevel:'internal' },
  { key:'todo.tenantId', label:'할일 테넌트', description:'할일 데이터의 내부 테넌트 ID.', valueType:'integer', storage:{table:'todos',column:'tenant_id'}, systemManaged:true, privacyLevel:'internal' },
  { key:'todo.gaId', label:'할일 GA', description:'할일 데이터의 GA 조직 ID.', valueType:'integer', storage:{table:'todos',column:'ga_id'}, systemManaged:true, privacyLevel:'internal' },
  { key:'todo.ownerUserId', label:'할일 소유자', description:'할일을 소유한 사용자 ID.', valueType:'string', storage:{table:'todos',column:'owner_user_id'}, systemManaged:true, privacyLevel:'internal' },
  { key:'todo.assigneeUserId', label:'할일 담당자', description:'할일을 수행할 담당 사용자 ID.', valueType:'string', storage:{table:'todos',column:'assignee_user_id'}, capabilities:{read:true,input:true,update:true} },
  { key:'todo.title', label:'할일 제목', description:'할일의 제목.', valueType:'string', storage:{table:'todos',column:'title'}, capabilities:{read:true,input:true,update:true} },
  { key:'todo.description', label:'할일 설명', description:'할일의 상세 내용.', valueType:'string', storage:{table:'todos',column:'description'}, capabilities:{read:true,input:true,update:true} },
  { key:'todo.dueDate', label:'할일 마감일', description:'할일 마감 예정 날짜.', valueType:'date', storage:{table:'todos',column:'due_date'}, capabilities:{read:true,input:true,update:true} },
  { key:'todo.dueTime', label:'할일 마감시간', description:'할일 마감 예정 시간.', valueType:'time', storage:{table:'todos',column:'due_time'}, capabilities:{read:true,input:true,update:true} },
  { key:'todo.status', label:'할일 상태', description:'할일 진행 상태.', valueType:'enum', storage:{table:'todos',column:'status'}, canonicalValues:['pending','completed','canceled'], capabilities:{read:true,input:true,update:true} },
  { key:'todo.priority', label:'할일 우선순위', description:'할일의 우선순위.', valueType:'enum', storage:{table:'todos',column:'priority'}, canonicalValues:['low','normal','high'], capabilities:{read:true,input:true,update:true} },
  { key:'todo.sourceType', label:'할일 생성 출처', description:'할일이 수동/메모/상담/PDF/전자문서/시스템 중 어디에서 생성되었는지 나타내는 출처.', valueType:'enum', storage:{table:'todos',column:'source_type'}, canonicalValues:['manual','customer_memo','consultation_note','pdf_document','e_document','system'], capabilities:{read:true} },
  { key:'todo.sourceId', label:'할일 출처 ID', description:'할일 생성 출처 레코드의 식별자.', valueType:'string', storage:{table:'todos',column:'source_id'}, systemManaged:true, privacyLevel:'internal' },
  { key:'todo.relatedEntityType', label:'할일 관련 대상 종류', description:'할일과 연결된 업무 엔티티 종류.', valueType:'string', storage:{table:'todos',column:'related_entity_type'}, capabilities:{read:true,input:true,update:true} },
  { key:'todo.relatedEntityId', label:'할일 관련 대상 ID', description:'할일과 연결된 업무 엔티티의 ID.', valueType:'string', storage:{table:'todos',column:'related_entity_id'}, capabilities:{read:true,input:true,update:true} },
  { key:'todo.metadata', label:'할일 확장정보', description:'할일의 구조화된 확장 메타데이터.', valueType:'json', storage:{table:'todos',column:'metadata'}, privacyLevel:'internal', capabilities:{read:true} },
  { key:'todo.createdAt', label:'할일 등록일', description:'할일 생성 시각.', valueType:'datetime', storage:{table:'todos',column:'created_at'}, systemManaged:true, privacyLevel:'internal' },
  { key:'todo.updatedAt', label:'할일 수정일', description:'할일 마지막 수정 시각.', valueType:'datetime', storage:{table:'todos',column:'updated_at'}, systemManaged:true, privacyLevel:'internal' },
  { key:'todo.completedAt', label:'할일 완료일', description:'할일 완료 처리 시각.', valueType:'datetime', storage:{table:'todos',column:'completed_at'}, systemManaged:true },
  { key:'todo.canceledAt', label:'할일 취소일', description:'할일 취소 처리 시각.', valueType:'datetime', storage:{table:'todos',column:'canceled_at'}, systemManaged:true },

  // calendar_items
  { key:'calendar.id', label:'일정 내부 ID', description:'일정/캘린더 항목 내부 UUID.', valueType:'string', storage:{table:'calendar_items',column:'id'}, systemManaged:true, privacyLevel:'internal' },
  { key:'calendar.gaId', label:'일정 GA', description:'일정 데이터 GA 조직 ID.', valueType:'integer', storage:{table:'calendar_items',column:'ga_id'}, systemManaged:true, privacyLevel:'internal' },
  { key:'calendar.ownerType', label:'일정 소유 대상 종류', description:'일정을 소유하는 대상 유형.', valueType:'enum', storage:{table:'calendar_items',column:'owner_type'}, canonicalValues:['user','team','customer','crm','workspace'], systemManaged:true, privacyLevel:'internal' },
  { key:'calendar.ownerId', label:'일정 소유 대상 ID', description:'일정을 소유하는 대상의 ID.', valueType:'string', storage:{table:'calendar_items',column:'owner_id'}, systemManaged:true, privacyLevel:'internal' },
  { key:'calendar.createdBy', label:'일정 등록 사용자', description:'일정을 생성한 사용자 ID.', valueType:'string', storage:{table:'calendar_items',column:'created_by'}, systemManaged:true, privacyLevel:'internal' },
  { key:'calendar.assignedTo', label:'일정 담당자', description:'일정이 배정된 사용자 ID.', valueType:'string', storage:{table:'calendar_items',column:'assigned_to'}, capabilities:{read:true,input:true,update:true} },
  { key:'calendar.itemType', label:'캘린더 항목 종류', description:'일정 또는 할일 구분.', valueType:'enum', storage:{table:'calendar_items',column:'item_type'}, canonicalValues:['schedule','todo'], capabilities:{read:true,input:true,update:true} },
  { key:'calendar.title', label:'일정 제목', description:'캘린더 항목 제목.', valueType:'string', storage:{table:'calendar_items',column:'title'}, capabilities:{read:true,input:true,update:true} },
  { key:'calendar.description', label:'일정 설명', description:'캘린더 항목 상세 내용.', valueType:'string', storage:{table:'calendar_items',column:'description'}, capabilities:{read:true,input:true,update:true} },
  { key:'calendar.startAt', label:'일정 시작시각', description:'일정 시작 날짜와 시간.', valueType:'datetime', storage:{table:'calendar_items',column:'start_at'}, capabilities:{read:true,input:true,update:true} },
  { key:'calendar.endAt', label:'일정 종료시각', description:'일정 종료 날짜와 시간.', valueType:'datetime', storage:{table:'calendar_items',column:'end_at'}, capabilities:{read:true,input:true,update:true} },
  { key:'calendar.dueDate', label:'캘린더 마감일', description:'할일형 캘린더 항목의 마감 날짜.', valueType:'date', storage:{table:'calendar_items',column:'due_date'}, capabilities:{read:true,input:true,update:true} },
  { key:'calendar.allDay', label:'종일 일정 여부', description:'종일 일정 여부.', valueType:'boolean', storage:{table:'calendar_items',column:'all_day'}, capabilities:{read:true,input:true,update:true} },
  { key:'calendar.status', label:'일정 상태', description:'캘린더 항목 진행 상태.', valueType:'enum', storage:{table:'calendar_items',column:'status'}, canonicalValues:['pending','completed','cancelled'], capabilities:{read:true,input:true,update:true} },
  { key:'calendar.priority', label:'일정 우선순위', description:'캘린더 항목 우선순위.', valueType:'enum', storage:{table:'calendar_items',column:'priority'}, canonicalValues:['low','normal','high'], capabilities:{read:true,input:true,update:true} },
  { key:'calendar.color', label:'일정 색상', description:'캘린더 표시 색상 값.', valueType:'string', storage:{table:'calendar_items',column:'color'}, capabilities:{read:true,input:true,update:true} },
  { key:'calendar.location', label:'일정 장소', description:'일정 장소.', valueType:'string', storage:{table:'calendar_items',column:'location'}, capabilities:{read:true,input:true,update:true} },
  { key:'calendar.visibility', label:'일정 공개범위', description:'일정의 개인/공유 공개 범위.', valueType:'enum', storage:{table:'calendar_items',column:'visibility'}, canonicalValues:['private','shared'], capabilities:{read:true,input:true,update:true} },
  { key:'calendar.sortOrder', label:'일정 정렬 순서', description:'캘린더 표시 순서.', valueType:'integer', storage:{table:'calendar_items',column:'sort_order'}, systemManaged:true, privacyLevel:'internal' },
  { key:'calendar.deletedAt', label:'일정 삭제 시각', description:'일정 소프트 삭제 시각.', valueType:'datetime', storage:{table:'calendar_items',column:'deleted_at'}, systemManaged:true, privacyLevel:'internal' },
  { key:'calendar.createdAt', label:'일정 등록일', description:'일정 생성 시각.', valueType:'datetime', storage:{table:'calendar_items',column:'created_at'}, systemManaged:true, privacyLevel:'internal' },
  { key:'calendar.updatedAt', label:'일정 수정일', description:'일정 마지막 수정 시각.', valueType:'datetime', storage:{table:'calendar_items',column:'updated_at'}, systemManaged:true, privacyLevel:'internal' },

  // customer_claim_requests
  { key:'claim.id', label:'청구요청 내부 ID', description:'고객 청구 요청 내부 ID.', valueType:'integer', storage:{table:'customer_claim_requests',column:'id'}, systemManaged:true, privacyLevel:'internal' },
  { key:'claim.agentId', label:'청구 담당 설계사', description:'청구 요청을 담당하는 사용자 ID.', valueType:'string', storage:{table:'customer_claim_requests',column:'agent_id'}, systemManaged:true, privacyLevel:'internal' },
  { key:'claim.customerId', label:'청구 고객 ID', description:'청구 요청이 연결된 고객 ID.', valueType:'integer', storage:{table:'customer_claim_requests',column:'customer_id'}, systemManaged:true, privacyLevel:'internal' },
  { key:'claim.linkId', label:'청구 고객앱 링크 ID', description:'청구 요청이 들어온 고객앱 링크 ID.', valueType:'integer', storage:{table:'customer_claim_requests',column:'link_id'}, systemManaged:true, privacyLevel:'internal' },
  { key:'claim.deviceId', label:'청구 요청 기기 ID', description:'청구 요청을 생성한 고객 기기 식별값.', valueType:'string', storage:{table:'customer_claim_requests',column:'device_id'}, systemManaged:true, privacyLevel:'internal' },
  { key:'claim.requestType', label:'청구 요청 종류', description:'고객앱에서 생성된 요청의 업무 종류.', valueType:'string', storage:{table:'customer_claim_requests',column:'request_type'}, capabilities:{read:true,input:true,update:true} },
  { key:'claim.status', label:'청구 상태', description:'청구 요청 처리 상태.', valueType:'enum', storage:{table:'customer_claim_requests',column:'status'}, canonicalValues:['requested','processing','done','rejected','canceled'], capabilities:{read:true,input:true,update:true} },
  { key:'claim.title', label:'청구 제목', description:'청구 요청 제목.', valueType:'string', storage:{table:'customer_claim_requests',column:'title'}, capabilities:{read:true,input:true,update:true} },
  { key:'claim.memo', label:'청구 메모', description:'청구 요청에 대한 메모.', valueType:'string', storage:{table:'customer_claim_requests',column:'memo'}, capabilities:{read:true,input:true,update:true} },
  { key:'claim.requesterName', label:'청구 요청자 이름', description:'청구를 요청한 사람의 이름.', valueType:'string', storage:{table:'customer_claim_requests',column:'requester_name'}, capabilities:{read:true,input:true,update:true} },
  { key:'claim.requesterBirthDate', label:'청구 요청자 생년월일', description:'청구 요청자의 생년월일 텍스트.', valueType:'string', storage:{table:'customer_claim_requests',column:'requester_birth_date'}, privacyLevel:'sensitive', capabilities:{read:true,input:true,update:true} },
  { key:'claim.requesterPhone', label:'청구 요청자 연락처', description:'청구 요청자의 연락처.', valueType:'string', storage:{table:'customer_claim_requests',column:'requester_phone'}, capabilities:{read:true,input:true,update:true} },
  { key:'claim.submittedAt', label:'청구 접수일', description:'청구 요청이 접수된 시각.', valueType:'datetime', storage:{table:'customer_claim_requests',column:'submitted_at'}, systemManaged:true },
  { key:'claim.processedAt', label:'청구 처리일', description:'청구 요청 처리 완료/처리 시각.', valueType:'datetime', storage:{table:'customer_claim_requests',column:'processed_at'}, systemManaged:true },
  { key:'claim.processedByUserId', label:'청구 처리 사용자', description:'청구 요청을 처리한 사용자 ID.', valueType:'string', storage:{table:'customer_claim_requests',column:'processed_by_user_id'}, systemManaged:true, privacyLevel:'internal' },
  { key:'claim.createdAt', label:'청구 생성일', description:'청구 요청 레코드 생성 시각.', valueType:'datetime', storage:{table:'customer_claim_requests',column:'created_at'}, systemManaged:true, privacyLevel:'internal' },
  { key:'claim.updatedAt', label:'청구 수정일', description:'청구 요청 마지막 수정 시각.', valueType:'datetime', storage:{table:'customer_claim_requests',column:'updated_at'}, systemManaged:true, privacyLevel:'internal' },

  // customer_claim_request_files
  { key:'claimFile.id', label:'청구파일 내부 ID', description:'청구 첨부파일 내부 ID.', valueType:'integer', storage:{table:'customer_claim_request_files',column:'id'}, systemManaged:true, privacyLevel:'internal' },
  { key:'claimFile.requestId', label:'청구파일 요청 ID', description:'첨부파일이 속한 청구 요청 ID.', valueType:'integer', storage:{table:'customer_claim_request_files',column:'request_id'}, systemManaged:true, privacyLevel:'internal' },
  { key:'claimFile.agentId', label:'청구파일 담당 설계사', description:'청구파일 담당 사용자 ID.', valueType:'string', storage:{table:'customer_claim_request_files',column:'agent_id'}, systemManaged:true, privacyLevel:'internal' },
  { key:'claimFile.customerId', label:'청구파일 고객 ID', description:'청구파일이 연결된 고객 ID.', valueType:'integer', storage:{table:'customer_claim_request_files',column:'customer_id'}, systemManaged:true, privacyLevel:'internal' },
  { key:'claimFile.storageKey', label:'청구파일 저장키', description:'스토리지 객체 키.', valueType:'string', storage:{table:'customer_claim_request_files',column:'storage_key'}, systemManaged:true, privacyLevel:'internal' },
  { key:'claimFile.fileName', label:'청구파일 이름', description:'고객이 업로드한 청구 첨부파일 이름.', valueType:'string', storage:{table:'customer_claim_request_files',column:'file_name'}, capabilities:{read:true,input:true} },
  { key:'claimFile.contentType', label:'청구파일 형식', description:'청구 첨부파일 MIME 타입.', valueType:'string', storage:{table:'customer_claim_request_files',column:'content_type'}, systemManaged:true },
  { key:'claimFile.fileSize', label:'청구파일 크기', description:'청구 첨부파일 바이트 크기.', valueType:'integer', storage:{table:'customer_claim_request_files',column:'file_size'}, systemManaged:true },
  { key:'claimFile.sortOrder', label:'청구파일 정렬 순서', description:'청구 첨부파일 표시 순서.', valueType:'integer', storage:{table:'customer_claim_request_files',column:'sort_order'}, systemManaged:true, privacyLevel:'internal' },
  { key:'claimFile.uploadedAt', label:'청구파일 업로드일', description:'첨부파일 업로드 시각.', valueType:'datetime', storage:{table:'customer_claim_request_files',column:'uploaded_at'}, systemManaged:true },
  { key:'claimFile.createdAt', label:'청구파일 생성일', description:'첨부파일 레코드 생성 시각.', valueType:'datetime', storage:{table:'customer_claim_request_files',column:'created_at'}, systemManaged:true, privacyLevel:'internal' },
  { key:'claimFile.updatedAt', label:'청구파일 수정일', description:'첨부파일 레코드 마지막 수정 시각.', valueType:'datetime', storage:{table:'customer_claim_request_files',column:'updated_at'}, systemManaged:true, privacyLevel:'internal' },

  // customer_app_profiles
  { key:'customerAppProfile.id', label:'고객앱 프로필 내부 ID', description:'고객앱 프로필 내부 ID.', valueType:'integer', storage:{table:'customer_app_profiles',column:'id'}, systemManaged:true, privacyLevel:'internal' },
  { key:'customerAppProfile.agentId', label:'고객앱 담당 설계사', description:'고객앱 프로필 담당 사용자 ID.', valueType:'string', storage:{table:'customer_app_profiles',column:'agent_id'}, systemManaged:true, privacyLevel:'internal' },
  { key:'customerAppProfile.customerId', label:'고객앱 고객 ID', description:'고객앱 프로필이 연결된 고객 ID.', valueType:'integer', storage:{table:'customer_app_profiles',column:'customer_id'}, systemManaged:true, privacyLevel:'internal' },
  { key:'customerAppProfile.deviceId', label:'고객앱 기기 ID', description:'고객앱 프로필 기기 식별값.', valueType:'string', storage:{table:'customer_app_profiles',column:'device_id'}, systemManaged:true, privacyLevel:'internal' },
  { key:'customerAppProfile.name', label:'고객앱 이름', description:'고객앱에서 입력한 사용자 이름.', valueType:'string', storage:{table:'customer_app_profiles',column:'name'}, capabilities:{read:true,input:true,update:true} },
  { key:'customerAppProfile.birthDate', label:'고객앱 생년월일', description:'고객앱에서 입력한 생년월일.', valueType:'string', storage:{table:'customer_app_profiles',column:'birth_date'}, privacyLevel:'sensitive', capabilities:{read:true,input:true,update:true} },
  { key:'customerAppProfile.phone', label:'고객앱 연락처', description:'고객앱에서 입력한 연락처.', valueType:'string', storage:{table:'customer_app_profiles',column:'phone'}, capabilities:{read:true,input:true,update:true} },
  { key:'customerAppProfile.createdAt', label:'고객앱 프로필 등록일', description:'고객앱 프로필 생성 시각.', valueType:'datetime', storage:{table:'customer_app_profiles',column:'created_at'}, systemManaged:true, privacyLevel:'internal' },
  { key:'customerAppProfile.updatedAt', label:'고객앱 프로필 수정일', description:'고객앱 프로필 마지막 수정 시각.', valueType:'datetime', storage:{table:'customer_app_profiles',column:'updated_at'}, systemManaged:true, privacyLevel:'internal' },

  // customer_files
  { key:'customerFile.id', label:'고객파일 내부 ID', description:'고객 저장 파일 내부 ID.', valueType:'integer', storage:{table:'customer_files',column:'id'}, systemManaged:true, privacyLevel:'internal' },
  { key:'customerFile.customerId', label:'고객파일 고객 ID', description:'파일이 연결된 고객 ID.', valueType:'integer', storage:{table:'customer_files',column:'customer_id'}, systemManaged:true, privacyLevel:'internal' },
  { key:'customerFile.userId', label:'고객파일 소유 사용자', description:'파일 소유 사용자 ID.', valueType:'string', storage:{table:'customer_files',column:'user_id'}, systemManaged:true, privacyLevel:'internal' },
  { key:'customerFile.gaId', label:'고객파일 GA', description:'파일 데이터 GA 조직 ID.', valueType:'integer', storage:{table:'customer_files',column:'ga_id'}, systemManaged:true, privacyLevel:'internal' },
  { key:'customerFile.content', label:'고객파일 텍스트 내용', description:'파일에서 추출되거나 함께 저장된 텍스트 내용.', valueType:'string', storage:{table:'customer_files',column:'content'}, privacyLevel:'sensitive', capabilities:{read:true,input:true,update:true} },
  { key:'customerFile.fileName', label:'고객파일 이름', description:'고객에게 저장된 파일 이름.', valueType:'string', storage:{table:'customer_files',column:'file_name'}, capabilities:{read:true,input:true,update:true} },
  { key:'customerFile.objectKey', label:'고객파일 저장키', description:'R2 등 객체 스토리지 내부 키.', valueType:'string', storage:{table:'customer_files',column:'object_key'}, systemManaged:true, privacyLevel:'internal' },
  { key:'customerFile.fileUrl', label:'고객파일 URL', description:'고객 파일 접근 경로.', valueType:'string', storage:{table:'customer_files',column:'file_url'}, systemManaged:true, privacyLevel:'internal' },
  { key:'customerFile.fileSize', label:'고객파일 크기', description:'파일 바이트 크기.', valueType:'integer', storage:{table:'customer_files',column:'file_size'}, systemManaged:true },
  { key:'customerFile.mimeType', label:'고객파일 형식', description:'파일 MIME 타입.', valueType:'string', storage:{table:'customer_files',column:'mime_type'}, systemManaged:true },
  { key:'customerFile.createdAt', label:'고객파일 등록일', description:'파일 레코드 생성 시각.', valueType:'datetime', storage:{table:'customer_files',column:'created_at'}, systemManaged:true, privacyLevel:'internal' },
  { key:'customerFile.expiresAt', label:'고객파일 만료일', description:'임시 파일의 만료 시각.', valueType:'datetime', storage:{table:'customer_files',column:'expires_at'}, systemManaged:true, privacyLevel:'internal' },
  { key:'customerFile.deletedAt', label:'고객파일 삭제 시각', description:'파일 소프트 삭제 시각.', valueType:'datetime', storage:{table:'customer_files',column:'deleted_at'}, systemManaged:true, privacyLevel:'internal' },

  // memo
  { key:'memo.id', label:'메모 내부 ID', description:'자유 메모 내부 UUID.', valueType:'string', storage:{table:'memo',column:'id'}, systemManaged:true, privacyLevel:'internal' },
  { key:'memo.userId', label:'메모 소유 사용자', description:'메모를 소유한 사용자 ID.', valueType:'string', storage:{table:'memo',column:'user_id'}, systemManaged:true, privacyLevel:'internal' },
  { key:'memo.gaId', label:'메모 GA', description:'메모 데이터 GA 조직 ID.', valueType:'integer', storage:{table:'memo',column:'ga_id'}, systemManaged:true, privacyLevel:'internal' },
  { key:'memo.content', label:'메모 내용', description:'사용자가 자유롭게 작성한 메모 내용.', valueType:'string', storage:{table:'memo',column:'content'}, capabilities:{read:true,input:true,update:true} },
  { key:'memo.x', label:'메모 X 위치', description:'메모 UI의 가로 위치.', valueType:'integer', storage:{table:'memo',column:'x'}, systemManaged:true, privacyLevel:'internal' },
  { key:'memo.y', label:'메모 Y 위치', description:'메모 UI의 세로 위치.', valueType:'integer', storage:{table:'memo',column:'y'}, systemManaged:true, privacyLevel:'internal' },
  { key:'memo.width', label:'메모 너비', description:'메모 UI 너비.', valueType:'integer', storage:{table:'memo',column:'width'}, systemManaged:true, privacyLevel:'internal' },
  { key:'memo.height', label:'메모 높이', description:'메모 UI 높이.', valueType:'integer', storage:{table:'memo',column:'height'}, systemManaged:true, privacyLevel:'internal' },
  { key:'memo.zIndex', label:'메모 레이어 순서', description:'메모 UI 겹침 순서.', valueType:'integer', storage:{table:'memo',column:'z_index'}, systemManaged:true, privacyLevel:'internal' },
  { key:'memo.fontSize', label:'메모 글자 크기', description:'메모 표시 글자 크기.', valueType:'integer', storage:{table:'memo',column:'font_size'}, capabilities:{read:true,input:true,update:true} },
  { key:'memo.fontWeight', label:'메모 글자 굵기', description:'메모 표시 글자 굵기.', valueType:'string', storage:{table:'memo',column:'font_weight'}, capabilities:{read:true,input:true,update:true} },
  { key:'memo.createdAt', label:'메모 등록일', description:'메모 생성 시각.', valueType:'datetime', storage:{table:'memo',column:'created_at'}, systemManaged:true, privacyLevel:'internal' },
  { key:'memo.updatedAt', label:'메모 수정일', description:'메모 마지막 수정 시각.', valueType:'datetime', storage:{table:'memo',column:'updated_at'}, systemManaged:true, privacyLevel:'internal' },

  // user_insurer_accounts
  { key:'insurerAccount.id', label:'보험사 계정 내부 ID', description:'보험사 계정관리 레코드 내부 ID.', valueType:'integer', storage:{table:'user_insurer_accounts',column:'id'}, systemManaged:true, privacyLevel:'internal' },
  { key:'insurerAccount.ownerUserId', label:'보험사 계정 소유 사용자', description:'보험사 계정을 소유한 사용자 ID.', valueType:'string', storage:{table:'user_insurer_accounts',column:'owner_user_id'}, systemManaged:true, privacyLevel:'internal' },
  { key:'insurerAccount.gaId', label:'보험사 계정 GA', description:'보험사 계정 데이터 GA 조직 ID.', valueType:'integer', storage:{table:'user_insurer_accounts',column:'ga_id'}, systemManaged:true, privacyLevel:'internal' },
  { key:'insurerAccount.category', label:'보험사 계정 분류', description:'보험사 계정의 회사/업무 분류.', valueType:'string', storage:{table:'user_insurer_accounts',column:'category'}, capabilities:{read:true,input:true,update:true} },
  { key:'insurerAccount.companyName', label:'보험사명', description:'로그인 계정을 사용하는 보험회사 이름.', valueType:'string', storage:{table:'user_insurer_accounts',column:'company_name'}, capabilities:{read:true,input:true,update:true} },
  { key:'insurerAccount.loginId', label:'보험사 로그인 ID', description:'보험회사 사이트 로그인 ID.', valueType:'string', storage:{table:'user_insurer_accounts',column:'login_id'}, privacyLevel:'identifying', capabilities:{read:true,input:true,update:true} },
  { key:'insurerAccount.loginPasswordEncrypted', label:'보험사 로그인 비밀번호 암호문', description:'보험회사 사이트 비밀번호의 암호화 저장값. AI에 원문을 노출하지 않는다.', valueType:'string', storage:{table:'user_insurer_accounts',column:'login_password_encrypted'}, privacyLevel:'secret', capabilities:{read:false,input:false,update:false} },
  { key:'insurerAccount.memo', label:'보험사 계정 메모', description:'보험사 계정에 대한 사용자 메모.', valueType:'string', storage:{table:'user_insurer_accounts',column:'memo'}, capabilities:{read:true,input:true,update:true} },
  { key:'insurerAccount.sortOrder', label:'보험사 계정 정렬 순서', description:'보험사 계정 목록 표시 순서.', valueType:'integer', storage:{table:'user_insurer_accounts',column:'sort_order'}, systemManaged:true, privacyLevel:'internal' },
  { key:'insurerAccount.isCustom', label:'사용자 추가 보험사 여부', description:'기본 보험사 목록이 아닌 사용자 직접 추가 항목인지 여부.', valueType:'boolean', storage:{table:'user_insurer_accounts',column:'is_custom'}, capabilities:{read:true,input:true,update:true} },
  { key:'insurerAccount.isArchived', label:'보험사 계정 보관 여부', description:'보험사 계정이 보관/숨김 처리되었는지 여부.', valueType:'boolean', storage:{table:'user_insurer_accounts',column:'is_archived'}, capabilities:{read:true,input:true,update:true} },
  { key:'insurerAccount.createdAt', label:'보험사 계정 등록일', description:'보험사 계정 생성 시각.', valueType:'datetime', storage:{table:'user_insurer_accounts',column:'created_at'}, systemManaged:true, privacyLevel:'internal' },
  { key:'insurerAccount.updatedAt', label:'보험사 계정 수정일', description:'보험사 계정 마지막 수정 시각.', valueType:'datetime', storage:{table:'user_insurer_accounts',column:'updated_at'}, systemManaged:true, privacyLevel:'internal' },

  // ta_call_assignments
  { key:'taAssignment.id', label:'TA 배정 내부 ID', description:'오늘의 TA 배정 레코드 내부 ID.', valueType:'integer', storage:{table:'ta_call_assignments',column:'id'}, systemManaged:true, privacyLevel:'internal' },
  { key:'taAssignment.userId', label:'TA 담당 사용자', description:'TA가 배정된 사용자 ID.', valueType:'string', storage:{table:'ta_call_assignments',column:'user_id'}, systemManaged:true, privacyLevel:'internal' },
  { key:'taAssignment.customerId', label:'TA 고객 ID', description:'TA 대상 고객 ID.', valueType:'integer', storage:{table:'ta_call_assignments',column:'customer_id'}, systemManaged:true, privacyLevel:'internal' },
  { key:'taAssignment.assignmentDate', label:'TA 배정일', description:'TA가 배정된 날짜.', valueType:'date', storage:{table:'ta_call_assignments',column:'assignment_date'}, systemManaged:true },
  { key:'taAssignment.rotationRound', label:'TA 회차', description:'TA 순환 배정 회차.', valueType:'integer', storage:{table:'ta_call_assignments',column:'rotation_round'}, systemManaged:true, privacyLevel:'internal' },
  { key:'taAssignment.status', label:'TA 상태', description:'TA 연락 처리 상태.', valueType:'enum', storage:{table:'ta_call_assignments',column:'status'}, canonicalValues:['not_called','completed','no_answer'], capabilities:{read:true,input:true,update:true} },
  { key:'taAssignment.customerNameSnapshot', label:'TA 고객명 스냅샷', description:'배정 시점 고객 이름 스냅샷.', valueType:'string', storage:{table:'ta_call_assignments',column:'customer_name_snapshot'}, systemManaged:true },
  { key:'taAssignment.customerPhoneSnapshot', label:'TA 연락처 스냅샷', description:'배정 시점 고객 연락처 스냅샷.', valueType:'string', storage:{table:'ta_call_assignments',column:'customer_phone_snapshot'}, systemManaged:true },
  { key:'taAssignment.customerBirthDateSnapshot', label:'TA 생년월일 스냅샷', description:'배정 시점 고객 생년월일 스냅샷.', valueType:'date', storage:{table:'ta_call_assignments',column:'customer_birth_date_snapshot'}, systemManaged:true, privacyLevel:'sensitive' },
  { key:'taAssignment.customerGenderSnapshot', label:'TA 성별 스냅샷', description:'배정 시점 고객 성별 canonical 값 스냅샷.', valueType:'enum', storage:{table:'ta_call_assignments',column:'customer_gender_snapshot'}, canonicalValues:['male','female'], systemManaged:true },
  { key:'taAssignment.completedAt', label:'TA 완료일', description:'TA 처리 완료 시각.', valueType:'datetime', storage:{table:'ta_call_assignments',column:'completed_at'}, systemManaged:true },
  { key:'taAssignment.createdAt', label:'TA 생성일', description:'TA 배정 생성 시각.', valueType:'datetime', storage:{table:'ta_call_assignments',column:'created_at'}, systemManaged:true, privacyLevel:'internal' },
  { key:'taAssignment.updatedAt', label:'TA 수정일', description:'TA 배정 마지막 수정 시각.', valueType:'datetime', storage:{table:'ta_call_assignments',column:'updated_at'}, systemManaged:true, privacyLevel:'internal' },

  // customer_relations
  { key:'customerRelation.id', label:'고객관계 내부 ID', description:'고객 관계 연결 내부 ID.', valueType:'integer', storage:{table:'customer_relations',column:'id'}, systemManaged:true, privacyLevel:'internal' },
  { key:'customerRelation.customerId', label:'기준 고객 ID', description:'관계 연결의 기준 고객 ID.', valueType:'integer', storage:{table:'customer_relations',column:'customer_id'}, systemManaged:true, privacyLevel:'internal' },
  { key:'customerRelation.relatedCustomerId', label:'연결 고객 ID', description:'기준 고객과 연결된 다른 고객 ID.', valueType:'integer', storage:{table:'customer_relations',column:'related_customer_id'}, capabilities:{read:true,input:true,update:true} },
  { key:'customerRelation.userId', label:'고객관계 소유 사용자', description:'고객 관계 데이터 소유 사용자 ID.', valueType:'string', storage:{table:'customer_relations',column:'user_id'}, systemManaged:true, privacyLevel:'internal' },
  { key:'customerRelation.gaId', label:'고객관계 GA', description:'고객 관계 데이터 GA 조직 ID.', valueType:'integer', storage:{table:'customer_relations',column:'ga_id'}, systemManaged:true, privacyLevel:'internal' },
  { key:'customerRelation.createdAt', label:'고객관계 등록일', description:'고객 관계 연결 생성 시각.', valueType:'datetime', storage:{table:'customer_relations',column:'created_at'}, systemManaged:true, privacyLevel:'internal' },

  // customer_premium_payment_methods (legacy/alternate premium payment card metadata)
  { key:'premiumPaymentMethod.id', label:'보험료 결제수단 내부 ID', description:'고객 보험료 결제수단 내부 ID.', valueType:'integer', storage:{table:'customer_premium_payment_methods',column:'id'}, systemManaged:true, privacyLevel:'internal' },
  { key:'premiumPaymentMethod.gaId', label:'보험료 결제수단 GA', description:'결제수단 GA 조직 ID.', valueType:'integer', storage:{table:'customer_premium_payment_methods',column:'ga_id'}, systemManaged:true, privacyLevel:'internal' },
  { key:'premiumPaymentMethod.ownerUserId', label:'보험료 결제수단 소유 사용자', description:'결제수단 소유 사용자 ID.', valueType:'string', storage:{table:'customer_premium_payment_methods',column:'owner_user_id'}, systemManaged:true, privacyLevel:'internal' },
  { key:'premiumPaymentMethod.customerId', label:'보험료 결제수단 고객 ID', description:'결제수단이 연결된 고객 ID.', valueType:'integer', storage:{table:'customer_premium_payment_methods',column:'customer_id'}, systemManaged:true, privacyLevel:'internal' },
  { key:'premiumPaymentMethod.insuranceCompany', label:'결제 보험회사', description:'해당 보험료 결제 계약의 보험회사.', valueType:'string', storage:{table:'customer_premium_payment_methods',column:'insurance_company'}, capabilities:{read:true,input:true,update:true} },
  { key:'premiumPaymentMethod.policyNumber', label:'증권번호', description:'보험계약 증권번호.', valueType:'string', storage:{table:'customer_premium_payment_methods',column:'policy_number'}, privacyLevel:'identifying', capabilities:{read:true,input:true,update:true} },
  { key:'premiumPaymentMethod.cardholderName', label:'카드 명의자', description:'보험료 결제 카드 명의자 이름.', valueType:'string', storage:{table:'customer_premium_payment_methods',column:'cardholder_name'}, privacyLevel:'sensitive', capabilities:{read:true,input:true,update:true} },
  { key:'premiumPaymentMethod.cardNumberCiphertext', label:'카드번호 암호문', description:'카드번호 암호화 저장값. AI에 원문 노출/직접 입력 금지.', valueType:'string', storage:{table:'customer_premium_payment_methods',column:'card_number_ciphertext'}, privacyLevel:'secret', capabilities:{read:false,input:false,update:false} },
  { key:'premiumPaymentMethod.encryptionKeyVersion', label:'카드 암호화키 버전', description:'카드번호 암호화에 사용한 키 버전.', valueType:'string', storage:{table:'customer_premium_payment_methods',column:'encryption_key_version'}, systemManaged:true, privacyLevel:'internal' },
  { key:'premiumPaymentMethod.cardNumberLast4', label:'카드번호 끝 4자리', description:'식별/표시용 카드번호 마지막 4자리.', valueType:'string', storage:{table:'customer_premium_payment_methods',column:'card_number_last4'}, privacyLevel:'sensitive', capabilities:{read:true} },
  { key:'premiumPaymentMethod.cardBrand', label:'카드사/브랜드', description:'카드 브랜드 또는 카드사 정보.', valueType:'string', storage:{table:'customer_premium_payment_methods',column:'card_brand'}, capabilities:{read:true,input:true,update:true} },
  { key:'premiumPaymentMethod.cardExpiryMonth', label:'카드 유효기간 월', description:'카드 유효기간 월.', valueType:'integer', storage:{table:'customer_premium_payment_methods',column:'card_expiry_month'}, privacyLevel:'sensitive', capabilities:{read:true,input:true,update:true} },
  { key:'premiumPaymentMethod.cardExpiryYear', label:'카드 유효기간 연도', description:'카드 유효기간 연도.', valueType:'integer', storage:{table:'customer_premium_payment_methods',column:'card_expiry_year'}, privacyLevel:'sensitive', capabilities:{read:true,input:true,update:true} },
  { key:'premiumPaymentMethod.memo', label:'보험료 결제수단 메모', description:'결제수단 관련 메모.', valueType:'string', storage:{table:'customer_premium_payment_methods',column:'memo'}, capabilities:{read:true,input:true,update:true} },
  { key:'premiumPaymentMethod.isActive', label:'보험료 결제수단 사용 여부', description:'결제수단 활성 여부.', valueType:'boolean', storage:{table:'customer_premium_payment_methods',column:'is_active'}, capabilities:{read:true,input:true,update:true} },
  { key:'premiumPaymentMethod.createdBy', label:'결제수단 등록 사용자', description:'결제수단을 등록한 사용자 ID.', valueType:'string', storage:{table:'customer_premium_payment_methods',column:'created_by'}, systemManaged:true, privacyLevel:'internal' },
  { key:'premiumPaymentMethod.updatedBy', label:'결제수단 수정 사용자', description:'결제수단을 마지막 수정한 사용자 ID.', valueType:'string', storage:{table:'customer_premium_payment_methods',column:'updated_by'}, systemManaged:true, privacyLevel:'internal' },
  { key:'premiumPaymentMethod.createdAt', label:'결제수단 등록일', description:'결제수단 생성 시각.', valueType:'datetime', storage:{table:'customer_premium_payment_methods',column:'created_at'}, systemManaged:true, privacyLevel:'internal' },
  { key:'premiumPaymentMethod.updatedAt', label:'결제수단 수정일', description:'결제수단 마지막 수정 시각.', valueType:'datetime', storage:{table:'customer_premium_payment_methods',column:'updated_at'}, systemManaged:true, privacyLevel:'internal' },
  { key:'premiumPaymentMethod.deletedAt', label:'결제수단 삭제 시각', description:'결제수단 소프트 삭제 시각.', valueType:'datetime', storage:{table:'customer_premium_payment_methods',column:'deleted_at'}, systemManaged:true, privacyLevel:'internal' },

  // customer_payment_cards
  { key:'paymentCard.id', label:'고객 카드 내부 ID', description:'카드수납 고객 카드 내부 ID.', valueType:'integer', storage:{table:'customer_payment_cards',column:'id'}, systemManaged:true, privacyLevel:'internal' },
  { key:'paymentCard.gaId', label:'고객 카드 GA', description:'카드 데이터 GA 조직 ID.', valueType:'integer', storage:{table:'customer_payment_cards',column:'ga_id'}, systemManaged:true, privacyLevel:'internal' },
  { key:'paymentCard.ownerUserId', label:'고객 카드 소유 사용자', description:'카드 데이터 소유 사용자 ID.', valueType:'string', storage:{table:'customer_payment_cards',column:'owner_user_id'}, systemManaged:true, privacyLevel:'internal' },
  { key:'paymentCard.customerId', label:'카드 고객 ID', description:'카드가 연결된 고객 ID.', valueType:'integer', storage:{table:'customer_payment_cards',column:'customer_id'}, systemManaged:true, privacyLevel:'internal' },
  { key:'paymentCard.label', label:'카드 별칭', description:'사용자가 지정한 카드 표시 이름.', valueType:'string', storage:{table:'customer_payment_cards',column:'label'}, capabilities:{read:true,input:true,update:true} },
  { key:'paymentCard.ownerName', label:'카드 명의자', description:'카드 명의자 이름.', valueType:'string', storage:{table:'customer_payment_cards',column:'card_owner_name'}, privacyLevel:'sensitive', capabilities:{read:true,input:true,update:true} },
  { key:'paymentCard.numberCiphertext', label:'카드번호 암호문', description:'카드번호 암호화 저장값. AI에 원문 노출/직접 입력 금지.', valueType:'string', storage:{table:'customer_payment_cards',column:'card_number_ciphertext'}, privacyLevel:'secret', capabilities:{read:false,input:false,update:false} },
  { key:'paymentCard.encryptionKeyVersion', label:'카드 암호화키 버전', description:'카드번호 암호화 키 버전.', valueType:'string', storage:{table:'customer_payment_cards',column:'encryption_key_version'}, systemManaged:true, privacyLevel:'internal' },
  { key:'paymentCard.last4', label:'카드번호 끝 4자리', description:'표시/식별용 카드번호 마지막 4자리.', valueType:'string', storage:{table:'customer_payment_cards',column:'card_number_last4'}, privacyLevel:'sensitive', capabilities:{read:true} },
  { key:'paymentCard.expiryMonth', label:'카드 유효기간 월', description:'카드 유효기간 월.', valueType:'integer', storage:{table:'customer_payment_cards',column:'card_expiry_month'}, privacyLevel:'sensitive', capabilities:{read:true,input:true,update:true} },
  { key:'paymentCard.expiryYear', label:'카드 유효기간 연도', description:'카드 유효기간 연도.', valueType:'integer', storage:{table:'customer_payment_cards',column:'card_expiry_year'}, privacyLevel:'sensitive', capabilities:{read:true,input:true,update:true} },
  { key:'paymentCard.isDefault', label:'기본 카드 여부', description:'고객의 기본 결제카드 여부.', valueType:'boolean', storage:{table:'customer_payment_cards',column:'is_default'}, capabilities:{read:true,input:true,update:true} },
  { key:'paymentCard.createdBy', label:'카드 등록 사용자', description:'카드를 등록한 사용자 ID.', valueType:'string', storage:{table:'customer_payment_cards',column:'created_by'}, systemManaged:true, privacyLevel:'internal' },
  { key:'paymentCard.updatedBy', label:'카드 수정 사용자', description:'카드를 마지막 수정한 사용자 ID.', valueType:'string', storage:{table:'customer_payment_cards',column:'updated_by'}, systemManaged:true, privacyLevel:'internal' },
  { key:'paymentCard.createdAt', label:'카드 등록일', description:'카드 레코드 생성 시각.', valueType:'datetime', storage:{table:'customer_payment_cards',column:'created_at'}, systemManaged:true, privacyLevel:'internal' },
  { key:'paymentCard.updatedAt', label:'카드 수정일', description:'카드 레코드 마지막 수정 시각.', valueType:'datetime', storage:{table:'customer_payment_cards',column:'updated_at'}, systemManaged:true, privacyLevel:'internal' },
  { key:'paymentCard.deletedAt', label:'카드 삭제 시각', description:'카드 소프트 삭제 시각.', valueType:'datetime', storage:{table:'customer_payment_cards',column:'deleted_at'}, systemManaged:true, privacyLevel:'internal' },

  // customer_card_payment_contracts
  { key:'paymentContract.id', label:'카드결제 계약 내부 ID', description:'카드수납 대상 계약 내부 ID.', valueType:'integer', storage:{table:'customer_card_payment_contracts',column:'id'}, systemManaged:true, privacyLevel:'internal' },
  { key:'paymentContract.gaId', label:'카드결제 계약 GA', description:'계약 데이터 GA 조직 ID.', valueType:'integer', storage:{table:'customer_card_payment_contracts',column:'ga_id'}, systemManaged:true, privacyLevel:'internal' },
  { key:'paymentContract.ownerUserId', label:'카드결제 계약 소유 사용자', description:'계약 데이터 소유 사용자 ID.', valueType:'string', storage:{table:'customer_card_payment_contracts',column:'owner_user_id'}, systemManaged:true, privacyLevel:'internal' },
  { key:'paymentContract.customerId', label:'카드결제 고객 ID', description:'결제 대상 계약의 고객 ID.', valueType:'integer', storage:{table:'customer_card_payment_contracts',column:'customer_id'}, systemManaged:true, privacyLevel:'internal' },
  { key:'paymentContract.paymentCardId', label:'결제 카드 ID', description:'계약에 연결된 결제 카드 ID.', valueType:'integer', storage:{table:'customer_card_payment_contracts',column:'payment_card_id'}, capabilities:{read:true,input:true,update:true} },
  { key:'paymentContract.insuranceCompany', label:'결제 보험회사', description:'계약의 보험회사.', valueType:'string', storage:{table:'customer_card_payment_contracts',column:'insurance_company'}, capabilities:{read:true,input:true,update:true} },
  { key:'paymentContract.policyNumber', label:'증권번호', description:'보험계약 증권번호.', valueType:'string', storage:{table:'customer_card_payment_contracts',column:'policy_number'}, privacyLevel:'identifying', capabilities:{read:true,input:true,update:true} },
  { key:'paymentContract.productName', label:'보험상품명', description:'보험계약 상품명.', valueType:'string', storage:{table:'customer_card_payment_contracts',column:'product_name'}, capabilities:{read:true,input:true,update:true} },
  { key:'paymentContract.premiumAmount', label:'보험료', description:'계약 월 보험료 또는 수납 대상 보험료 금액.', valueType:'number', storage:{table:'customer_card_payment_contracts',column:'premium_amount'}, capabilities:{read:true,input:true,update:true} },
  { key:'paymentContract.paymentDay', label:'보험료 결제일', description:'매월 보험료 결제 예정 일자(1~31).', valueType:'integer', storage:{table:'customer_card_payment_contracts',column:'payment_day'}, capabilities:{read:true,input:true,update:true} },
  { key:'paymentContract.memo', label:'카드결제 계약 메모', description:'결제 대상 계약 관련 메모.', valueType:'string', storage:{table:'customer_card_payment_contracts',column:'memo'}, capabilities:{read:true,input:true,update:true} },
  { key:'paymentContract.status', label:'카드결제 계약 상태', description:'카드수납 대상 계약의 진행 상태.', valueType:'enum', storage:{table:'customer_card_payment_contracts',column:'status'}, canonicalValues:['PENDING','PAUSED'], capabilities:{read:true,input:true,update:true} },
  { key:'paymentContract.lastCompletedAt', label:'최근 결제완료일', description:'가장 최근 카드결제 완료 시각.', valueType:'datetime', storage:{table:'customer_card_payment_contracts',column:'last_completed_at'}, systemManaged:true },
  { key:'paymentContract.createdBy', label:'카드결제 계약 등록 사용자', description:'계약을 등록한 사용자 ID.', valueType:'string', storage:{table:'customer_card_payment_contracts',column:'created_by'}, systemManaged:true, privacyLevel:'internal' },
  { key:'paymentContract.updatedBy', label:'카드결제 계약 수정 사용자', description:'계약을 마지막 수정한 사용자 ID.', valueType:'string', storage:{table:'customer_card_payment_contracts',column:'updated_by'}, systemManaged:true, privacyLevel:'internal' },
  { key:'paymentContract.createdAt', label:'카드결제 계약 등록일', description:'결제 대상 계약 생성 시각.', valueType:'datetime', storage:{table:'customer_card_payment_contracts',column:'created_at'}, systemManaged:true, privacyLevel:'internal' },
  { key:'paymentContract.updatedAt', label:'카드결제 계약 수정일', description:'결제 대상 계약 마지막 수정 시각.', valueType:'datetime', storage:{table:'customer_card_payment_contracts',column:'updated_at'}, systemManaged:true, privacyLevel:'internal' },
  { key:'paymentContract.deletedAt', label:'카드결제 계약 삭제 시각', description:'결제 대상 계약 소프트 삭제 시각.', valueType:'datetime', storage:{table:'customer_card_payment_contracts',column:'deleted_at'}, systemManaged:true, privacyLevel:'internal' },

  // customer_card_payment_completions
  { key:'paymentCompletion.id', label:'카드결제 완료 내부 ID', description:'월별 카드결제 완료 기록 내부 ID.', valueType:'integer', storage:{table:'customer_card_payment_completions',column:'id'}, systemManaged:true, privacyLevel:'internal' },
  { key:'paymentCompletion.gaId', label:'카드결제 완료 GA', description:'완료 기록 GA 조직 ID.', valueType:'integer', storage:{table:'customer_card_payment_completions',column:'ga_id'}, systemManaged:true, privacyLevel:'internal' },
  { key:'paymentCompletion.contractId', label:'카드결제 계약 ID', description:'완료 처리된 카드결제 계약 ID.', valueType:'integer', storage:{table:'customer_card_payment_completions',column:'contract_id'}, systemManaged:true, privacyLevel:'internal' },
  { key:'paymentCompletion.customerId', label:'카드결제 고객 ID', description:'완료 기록의 고객 ID.', valueType:'integer', storage:{table:'customer_card_payment_completions',column:'customer_id'}, systemManaged:true, privacyLevel:'internal' },
  { key:'paymentCompletion.targetMonth', label:'결제 대상 월', description:'보험료 결제가 완료된 대상 월(YYYY-MM).', valueType:'string', storage:{table:'customer_card_payment_completions',column:'target_month'}, capabilities:{read:true,input:true,update:false} },
  { key:'paymentCompletion.completedAt', label:'결제 완료 시각', description:'보험료 카드결제를 완료 처리한 시각.', valueType:'datetime', storage:{table:'customer_card_payment_completions',column:'completed_at'}, systemManaged:true },
  { key:'paymentCompletion.completedBy', label:'결제 완료 사용자', description:'결제 완료 처리를 한 사용자 ID.', valueType:'string', storage:{table:'customer_card_payment_completions',column:'completed_by'}, systemManaged:true, privacyLevel:'internal' },
  { key:'paymentCompletion.memo', label:'결제 완료 메모', description:'월별 결제 완료 기록 메모.', valueType:'string', storage:{table:'customer_card_payment_completions',column:'memo'}, capabilities:{read:true,input:true,update:true} },
  { key:'paymentCompletion.createdAt', label:'결제 완료 기록 생성일', description:'결제 완료 기록 생성 시각.', valueType:'datetime', storage:{table:'customer_card_payment_completions',column:'created_at'}, systemManaged:true, privacyLevel:'internal' },
]
