import type {
  CustomerFieldRegistryEntry,
} from './customerTemplateRegistry.types'

/** Registry 스키마와 동기화되는 기본 버전 문자열 */
const SV = '0.1'

const v = ({
  validation = {},
}: {
  validation?: CustomerFieldRegistryEntry['validation']
} = {}): CustomerFieldRegistryEntry['validation'] => ({ ...validation })

/**
 * Canonical fieldKey → 정의.
 * 레거시 숏키(alias) 해석은 registry utils 의 alias 맵으로 처리한다.
 */
export const CUSTOMER_FIELD_REGISTRY_BY_KEY: Readonly<
  Record<string, Readonly<CustomerFieldRegistryEntry>>
> = Object.freeze({
  'customer.name': Object.freeze({
    fieldKey: 'customer.name',
    label: '이름',
    category: 'core',
    domains: Object.freeze(['core']),
    widget: 'text',
    valueType: 'string',
    requiredDefault: true,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v({ validation: { maxLength: 200 } }),
    description: '고객 표시명·실명.',
    storageMapping: { kind: 'legacyColumn', column: 'name' },
    status: 'active',
    introducedInSchemaVersion: SV,
  }),
  'customer.phone': Object.freeze({
    fieldKey: 'customer.phone',
    label: '연락처',
    category: 'contact',
    domains: Object.freeze(['core']),
    widget: 'phone',
    valueType: 'string',
    requiredDefault: true,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v({ validation: { maxLength: 64 } }),
    description: '대표 전화번호.',
    storageMapping: { kind: 'legacyColumn', column: 'phone' },
    status: 'active',
    introducedInSchemaVersion: SV,
  }),
  'customer.email': Object.freeze({
    fieldKey: 'customer.email',
    label: '이메일',
    category: 'contact',
    domains: Object.freeze(['core']),
    widget: 'text',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: false,
    privacyLevel: 'normal',
    validation: v({ validation: { maxLength: 320 } }),
    description: '선택 연락처. 레거시 스키마에는 없을 수 있음.',
    storageMapping: {
      kind: 'unmapped',
      reason: 'legacy customers row — optional future column',
    },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'customer.address': Object.freeze({
    fieldKey: 'customer.address',
    label: '주소',
    category: 'contact',
    domains: Object.freeze(['core']),
    widget: 'textarea',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v(),
    description: '우편/거주 주소 텍스트.',
    storageMapping: { kind: 'legacyColumn', column: 'address' },
    status: 'active',
    introducedInSchemaVersion: SV,
  }),
  'customer.birthDate': Object.freeze({
    fieldKey: 'customer.birthDate',
    label: '생년월일',
    category: 'personal',
    domains: Object.freeze(['core', 'insurance']),
    widget: 'date',
    valueType: 'date',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'sensitive',
    validation: v(),
    description: '생년월일(ISO date string 등 저장 형식은 저장소 책임).',
    storageMapping: { kind: 'legacyColumn', column: 'birth_date' },
    status: 'active',
    introducedInSchemaVersion: SV,
  }),
  'customer.memo': Object.freeze({
    fieldKey: 'customer.memo',
    label: '메모',
    category: 'document',
    domains: Object.freeze(['core']),
    widget: 'textarea',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v(),
    description:
      '인라인/요약 메모. 실제 저장은 notes JSON·별도 테이블일 수 있다.',
    storageMapping: { kind: 'jsonPath', path: 'notes' },
    status: 'active',
    introducedInSchemaVersion: SV,
  }),
  'customer.status': Object.freeze({
    fieldKey: 'customer.status',
    label: '상태',
    category: 'core',
    domains: Object.freeze(['core']),
    widget: 'select',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: false,
    privacyLevel: 'normal',
    validation: v(),
    description: '워크플로 상태(프로젝트 enum 연결 예정).',
    storageMapping: { kind: 'unmapped', reason: 'not yet in legacy row' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'customer.assigneeUserId': Object.freeze({
    fieldKey: 'customer.assigneeUserId',
    label: '담당자',
    category: 'core',
    domains: Object.freeze(['core']),
    widget: 'select',
    valueType: 'number',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v(),
    description: '담당 설계사/직원 user id.',
    storageMapping: { kind: 'legacyColumn', column: 'user_id' },
    status: 'active',
    introducedInSchemaVersion: SV,
  }),
  'customer.tags': Object.freeze({
    fieldKey: 'customer.tags',
    label: '태그',
    category: 'core',
    domains: Object.freeze(['core']),
    widget: 'tags',
    valueType: 'json',
    requiredDefault: false,
    visibleDefault: false,
    privacyLevel: 'normal',
    validation: v(),
    description: '다중 태그. 레거시는 미구현일 수 있음.',
    storageMapping: {
      kind: 'unmapped',
      reason: 'tags storage TBD — separate table or JSON',
    },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'customer.createdAt': Object.freeze({
    fieldKey: 'customer.createdAt',
    label: '등록일',
    category: 'core',
    domains: Object.freeze(['core']),
    widget: 'readonly-text',
    valueType: 'date',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v(),
    description: '레코드 생성 시각.',
    storageMapping: { kind: 'legacyColumn', column: 'created_at' },
    status: 'active',
    introducedInSchemaVersion: SV,
  }),
  /** insuranceCustomerTemplate v0.1 의 `isFavorite` 와 매핑 */
  'customer.isFavorite': Object.freeze({
    fieldKey: 'customer.isFavorite',
    label: '중요 고객',
    category: 'core',
    domains: Object.freeze(['core']),
    widget: 'boolean',
    valueType: 'boolean',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v(),
    description: '즐겨찾기/중요 플래그.',
    storageMapping: { kind: 'legacyColumn', column: 'is_favorite' },
    status: 'active',
    introducedInSchemaVersion: SV,
  }),
  /** insuranceCustomerTemplate v0.1 의 `customerCode` 와 매핑 */
  'customer.customerCode': Object.freeze({
    fieldKey: 'customer.customerCode',
    label: '고객번호',
    category: 'core',
    domains: Object.freeze(['core']),
    widget: 'readonly-text',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v({ validation: { maxLength: 64 } }),
    description: '내부 고객 식별 코드.',
    storageMapping: { kind: 'legacyColumn', column: 'customer_code' },
    status: 'active',
    introducedInSchemaVersion: SV,
  }),
  'insurance.ssn': Object.freeze({
    fieldKey: 'insurance.ssn',
    label: '주민등록번호',
    category: 'personal',
    domains: Object.freeze(['insurance']),
    widget: 'ssn',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'identifying',
    validation: v({ validation: { pattern: '^\\d{6}-\\d{7}$' } }),
    description: '식별번호. 마스킹·저장 규격은 규제 레이어.',
    storageMapping: { kind: 'legacyColumn', column: 'ssn' },
    status: 'active',
    introducedInSchemaVersion: SV,
  }),
  'insurance.insuranceAge': Object.freeze({
    fieldKey: 'insurance.insuranceAge',
    label: '보험나이',
    category: 'insurance',
    domains: Object.freeze(['insurance']),
    widget: 'number',
    valueType: 'number',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v({ validation: { minimum: 0, maximum: 150 } }),
    description: '상령·보험나이 표시값(파생 가능).',
    storageMapping: { kind: 'legacyColumn', column: 'insurance_age' },
    status: 'active',
    introducedInSchemaVersion: SV,
  }),
  'insurance.nextAgeDate': Object.freeze({
    fieldKey: 'insurance.nextAgeDate',
    label: '상령일',
    category: 'insurance',
    domains: Object.freeze(['insurance']),
    widget: 'date',
    valueType: 'date',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v(),
    description: '다음 상령일.',
    storageMapping: { kind: 'legacyColumn', column: 'next_age_date' },
    status: 'active',
    introducedInSchemaVersion: SV,
  }),
  'customer.gender': Object.freeze({
    fieldKey: 'customer.gender',
    label: '성별',
    category: 'personal',
    domains: Object.freeze(['core', 'insurance']),
    widget: 'select',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v({ validation: { enumValues: Object.freeze(['M', 'F', 'OTHER']) } }),
    description: '성별 선택.',
    storageMapping: { kind: 'legacyColumn', column: 'gender' },
    status: 'active',
    introducedInSchemaVersion: SV,
  }),
  'customer.job': Object.freeze({
    fieldKey: 'customer.job',
    label: '직업·회사',
    category: 'personal',
    domains: Object.freeze(['core', 'insurance']),
    widget: 'text',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v({ validation: { maxLength: 500 } }),
    description: '직업·근무처.',
    storageMapping: { kind: 'legacyColumn', column: 'job' },
    status: 'active',
    introducedInSchemaVersion: SV,
  }),
  'customer.height': Object.freeze({
    fieldKey: 'customer.height',
    label: '키',
    category: 'personal',
    domains: Object.freeze(['core', 'insurance', 'gym']),
    widget: 'text',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'sensitive',
    validation: v({ validation: { maxLength: 32 } }),
    description: '신장(cm 등 단위 문자열 허용).',
    storageMapping: { kind: 'legacyColumn', column: 'height' },
    status: 'active',
    introducedInSchemaVersion: SV,
  }),
  'customer.weight': Object.freeze({
    fieldKey: 'customer.weight',
    label: '몸무게',
    category: 'personal',
    domains: Object.freeze(['core', 'insurance', 'gym']),
    widget: 'text',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'sensitive',
    validation: v({ validation: { maxLength: 32 } }),
    description: '체중.',
    storageMapping: { kind: 'legacyColumn', column: 'weight' },
    status: 'active',
    introducedInSchemaVersion: SV,
  }),
  'insurance.medical': Object.freeze({
    fieldKey: 'insurance.medical',
    label: '의료·건강 고지',
    category: 'insurance',
    domains: Object.freeze(['insurance']),
    widget: 'textarea',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'sensitive',
    validation: v(),
    description: '의료 고지 요약 텍스트.',
    storageMapping: { kind: 'legacyColumn', column: 'medical' },
    status: 'active',
    introducedInSchemaVersion: SV,
  }),
  'insurance.drivingText': Object.freeze({
    fieldKey: 'insurance.drivingText',
    label: '운전(텍스트)',
    category: 'insurance',
    domains: Object.freeze(['insurance']),
    widget: 'text',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v(),
    description: '운전 상태 자유 입력.',
    storageMapping: { kind: 'legacyColumn', column: 'driving' },
    status: 'active',
    introducedInSchemaVersion: SV,
  }),
  'insurance.isDriver': Object.freeze({
    fieldKey: 'insurance.isDriver',
    label: '운전 여부',
    category: 'insurance',
    domains: Object.freeze(['insurance']),
    widget: 'boolean',
    valueType: 'boolean',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v(),
    description: '운전자 여부.',
    storageMapping: { kind: 'legacyColumn', column: 'is_driver' },
    status: 'active',
    introducedInSchemaVersion: SV,
  }),
  'vehicle.carType': Object.freeze({
    fieldKey: 'vehicle.carType',
    label: '차종',
    category: 'vehicle',
    domains: Object.freeze(['insurance']),
    widget: 'text',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v({ validation: { maxLength: 120 } }),
    description: '대표 차종(복수 차량 시 expansion row).',
    storageMapping: { kind: 'legacyColumn', column: 'car_type' },
    status: 'active',
    introducedInSchemaVersion: SV,
  }),
  'vehicle.carNumber': Object.freeze({
    fieldKey: 'vehicle.carNumber',
    label: '차량번호',
    category: 'vehicle',
    domains: Object.freeze(['insurance']),
    widget: 'text',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v({ validation: { maxLength: 32 } }),
    description: '번호판 번호.',
    storageMapping: { kind: 'legacyColumn', column: 'car_number' },
    status: 'active',
    introducedInSchemaVersion: SV,
  }),
  'vehicle.carModel': Object.freeze({
    fieldKey: 'vehicle.carModel',
    label: '차량 모델',
    category: 'vehicle',
    domains: Object.freeze(['insurance']),
    widget: 'text',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v({ validation: { maxLength: 200 } }),
    description: '세부 모델명.',
    storageMapping: { kind: 'legacyColumn', column: 'car_model' },
    status: 'active',
    introducedInSchemaVersion: SV,
  }),
  'vehicle.carYear': Object.freeze({
    fieldKey: 'vehicle.carYear',
    label: '차량 연식',
    category: 'vehicle',
    domains: Object.freeze(['insurance']),
    widget: 'text',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v({ validation: { maxLength: 8 } }),
    description: '연식 문자열 또는 연도 숫자.',
    storageMapping: { kind: 'legacyColumn', column: 'car_year' },
    status: 'active',
    introducedInSchemaVersion: SV,
  }),
  'insurance.renewalDate': Object.freeze({
    fieldKey: 'insurance.renewalDate',
    label: '만기·갱신 예정일',
    category: 'insurance',
    domains: Object.freeze(['insurance']),
    widget: 'date',
    valueType: 'date',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v(),
    description: '자동차/대표증권 등 갱신일.',
    storageMapping: { kind: 'legacyColumn', column: 'renewal_date' },
    status: 'active',
    introducedInSchemaVersion: SV,
  }),
  'gym.membershipType': Object.freeze({
    fieldKey: 'gym.membershipType',
    label: '회원권 유형',
    category: 'gym',
    domains: Object.freeze(['gym']),
    widget: 'select',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v(),
    description: '헬스장 회원 유형.',
    storageMapping: { kind: 'unmapped', reason: 'future gym schema' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'gym.membershipStartDate': Object.freeze({
    fieldKey: 'gym.membershipStartDate',
    label: '회원권 시작일',
    category: 'gym',
    domains: Object.freeze(['gym']),
    widget: 'date',
    valueType: 'date',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v(),
    description: '시작일.',
    storageMapping: { kind: 'unmapped', reason: 'future gym schema' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'gym.membershipEndDate': Object.freeze({
    fieldKey: 'gym.membershipEndDate',
    label: '회원권 종료일',
    category: 'gym',
    domains: Object.freeze(['gym']),
    widget: 'date',
    valueType: 'date',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v(),
    description: '만료일.',
    storageMapping: { kind: 'unmapped', reason: 'future gym schema' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'gym.ptCount': Object.freeze({
    fieldKey: 'gym.ptCount',
    label: 'PT 잔여',
    category: 'gym',
    domains: Object.freeze(['gym']),
    widget: 'number',
    valueType: 'number',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v({ validation: { minimum: 0 } }),
    description: 'PT 회차 카운터.',
    storageMapping: { kind: 'unmapped', reason: 'future gym schema' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'gym.workoutGoal': Object.freeze({
    fieldKey: 'gym.workoutGoal',
    label: '운동 목표',
    category: 'gym',
    domains: Object.freeze(['gym']),
    widget: 'textarea',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v(),
    description: '목표 서술.',
    storageMapping: { kind: 'unmapped', reason: 'future gym schema' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'alcohol.businessNumber': Object.freeze({
    fieldKey: 'alcohol.businessNumber',
    label: '사업자등록번호',
    category: 'business',
    domains: Object.freeze(['alcohol']),
    widget: 'text',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v(),
    description: '도매 거래처 사업자 번호.',
    storageMapping: { kind: 'unmapped', reason: 'future alcohol schema' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'alcohol.storeName': Object.freeze({
    fieldKey: 'alcohol.storeName',
    label: '매장명',
    category: 'business',
    domains: Object.freeze(['alcohol']),
    widget: 'text',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v(),
    description: '거래처/매장명.',
    storageMapping: { kind: 'unmapped', reason: 'future alcohol schema' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'alcohol.deliveryAddress': Object.freeze({
    fieldKey: 'alcohol.deliveryAddress',
    label: '배송지',
    category: 'contact',
    domains: Object.freeze(['alcohol']),
    widget: 'textarea',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v(),
    description: '배달 주소.',
    storageMapping: { kind: 'unmapped', reason: 'future alcohol schema' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'alcohol.paymentTerms': Object.freeze({
    fieldKey: 'alcohol.paymentTerms',
    label: '결제 조건',
    category: 'business',
    domains: Object.freeze(['alcohol']),
    widget: 'textarea',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v(),
    description: '결제·세금계산서 조건.',
    storageMapping: { kind: 'unmapped', reason: 'future alcohol schema' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'alcohol.orderCycle': Object.freeze({
    fieldKey: 'alcohol.orderCycle',
    label: '발주 주기',
    category: 'business',
    domains: Object.freeze(['alcohol']),
    widget: 'select',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v(),
    description: '정기 발주 패턴.',
    storageMapping: { kind: 'unmapped', reason: 'future alcohol schema' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'gov.applicationType': Object.freeze({
    fieldKey: 'gov.applicationType',
    label: '신청 유형',
    category: 'document',
    domains: Object.freeze(['gov_support']),
    widget: 'select',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v(),
    description: '정부 지원 신청 카테고리.',
    storageMapping: {
      kind: 'unmapped',
      reason: 'future gov_support schema',
    },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'gov.supportProgram': Object.freeze({
    fieldKey: 'gov.supportProgram',
    label: '지원 프로그램',
    category: 'document',
    domains: Object.freeze(['gov_support']),
    widget: 'text',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v(),
    description: '프로그램명.',
    storageMapping: {
      kind: 'unmapped',
      reason: 'future gov_support schema',
    },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'gov.documentStatus': Object.freeze({
    fieldKey: 'gov.documentStatus',
    label: '서류 상태',
    category: 'document',
    domains: Object.freeze(['gov_support']),
    widget: 'select',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v(),
    description: '제출 서류 진행 상태.',
    storageMapping: {
      kind: 'unmapped',
      reason: 'future gov_support schema',
    },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'gov.applicationStatus': Object.freeze({
    fieldKey: 'gov.applicationStatus',
    label: '신청 상태',
    category: 'document',
    domains: Object.freeze(['gov_support']),
    widget: 'select',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v(),
    description: '정부 프로그램 심사·승인 단계.',
    storageMapping: {
      kind: 'unmapped',
      reason: 'future gov_support schema',
    },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
})
