import type { FeatureModuleRegistryEntry } from './customerTemplateRegistry.types'

/**
 * Canonical featureId → 정의.
 * tenant.config.crm.featureFlags 키로 tabId 가 쓰일 수 있으나,
 * 본 레지스트리의 식별자는 featureBinding 문자열이다.
 */
export const FEATURE_MODULE_REGISTRY_BY_ID: Readonly<
  Record<string, Readonly<FeatureModuleRegistryEntry>>
> = Object.freeze({
  'crm-storage-files': Object.freeze({
    featureId: 'crm-storage-files',
    label: '파일',
    category: 'crm-core',
    moduleType: 'detailTab',
    domains: Object.freeze(['core']),
    description: '고객별 파일 저장소 패널.',
    requiredPermissions: Object.freeze([]),
    configSchema: Object.freeze({
      title: 'CrmFilesConfig',
      type: 'object',
      properties: {},
    }),
    routeBinding: { pathPattern: '/customers/:customerId/files', routeName: 'customer-files' },
    apiBinding: { tag: 'customer-files', pathPrefix: '/customers/:customerId/files' },
    dependencies: Object.freeze([]),
    tenantConfigKeys: Object.freeze(['feature.files']),
    status: 'active',
  }),
  'crm-consultations': Object.freeze({
    featureId: 'crm-consultations',
    label: '상담',
    category: 'crm-core',
    moduleType: 'detailTab',
    domains: Object.freeze(['core']),
    description: '상담 이력·기록 패널.',
    requiredPermissions: Object.freeze([]),
    configSchema: Object.freeze({
      title: 'CrmConsultationsConfig',
      type: 'object',
      properties: {},
    }),
    routeBinding: {
      pathPattern: '/customers/:customerId/consultations',
      routeName: 'customer-consultations',
    },
    apiBinding: { tag: 'customer-consultations' },
    dependencies: Object.freeze([]),
    tenantConfigKeys: Object.freeze(['feature.consultations']),
    status: 'active',
  }),
  'crm-inline-notes': Object.freeze({
    featureId: 'crm-inline-notes',
    label: '메모',
    category: 'crm-core',
    moduleType: 'detailTab',
    domains: Object.freeze(['core']),
    description: '인라인 메모 패널(워크스페이스·사이드).',
    requiredPermissions: Object.freeze([]),
    configSchema: Object.freeze({ title: 'CrmMemoConfig', type: 'object', properties: {} }),
    routeBinding: { pathPattern: '/customers/:customerId/memos', routeName: 'customer-memos' },
    dependencies: Object.freeze([]),
    tenantConfigKeys: Object.freeze(['feature.memos']),
    status: 'active',
  }),
  'crm-linked-customers': Object.freeze({
    featureId: 'crm-linked-customers',
    label: '연결 고객',
    category: 'crm-core',
    moduleType: 'panel',
    domains: Object.freeze(['core']),
    description: '가족·법인 등 연결된 고객 관계 관리.',
    requiredPermissions: Object.freeze([]),
    configSchema: Object.freeze({
      title: 'CrmLinkedCustomersConfig',
      type: 'object',
      properties: {},
    }),
    dependencies: Object.freeze([]),
    tenantConfigKeys: Object.freeze(['feature.linkedCustomers']),
    status: 'active',
  }),
  'notifications-sms-gateway': Object.freeze({
    featureId: 'notifications-sms-gateway',
    label: 'SMS 알림 게이트웨이',
    category: 'communications',
    moduleType: 'integration',
    domains: Object.freeze(['core']),
    description: 'SMS 발송·템플릿 연계.',
    requiredPermissions: Object.freeze(['notifications.send']),
    configSchema: Object.freeze({
      title: 'SmsGatewayConfig',
      type: 'object',
      properties: {},
    }),
    dependencies: Object.freeze([]),
    tenantConfigKeys: Object.freeze(['integrations.sms']),
    status: 'active',
  }),
  'esign-send': Object.freeze({
    featureId: 'esign-send',
    label: '전자서명 발송',
    category: 'documents',
    moduleType: 'action',
    domains: Object.freeze(['core']),
    description: '전자서명 문서 발송 플로.',
    requiredPermissions: Object.freeze([]),
    configSchema: Object.freeze({ title: 'EsignSendConfig', type: 'object', properties: {} }),
    dependencies: Object.freeze([]),
    tenantConfigKeys: Object.freeze(['integrations.esign']),
    status: 'active',
  }),
  'esign-history': Object.freeze({
    featureId: 'esign-history',
    label: '전자서명 이력',
    category: 'documents',
    moduleType: 'panel',
    domains: Object.freeze(['core']),
    description: '전자서명 요청·완료 이력.',
    requiredPermissions: Object.freeze([]),
    configSchema: Object.freeze({ title: 'EsignHistoryConfig', type: 'object', properties: {} }),
    dependencies: Object.freeze(['esign-send']),
    tenantConfigKeys: Object.freeze(['integrations.esign']),
    status: 'active',
  }),
  'documents-send': Object.freeze({
    featureId: 'documents-send',
    label: '문서 발송',
    category: 'documents',
    moduleType: 'action',
    domains: Object.freeze(['core']),
    description: '일반 문서 발송(이메일/파일 링크 등).',
    requiredPermissions: Object.freeze([]),
    configSchema: Object.freeze({
      title: 'DocumentsSendConfig',
      type: 'object',
      properties: {},
    }),
    dependencies: Object.freeze([]),
    tenantConfigKeys: Object.freeze(['integrations.documents']),
    status: 'preview',
  }),
  'permissions-scope': Object.freeze({
    featureId: 'permissions-scope',
    label: '권한 범위',
    category: 'admin',
    moduleType: 'backgroundJob',
    domains: Object.freeze(['core']),
    description: '조직 단위 접근 통제 노출 훅(횡단 관심사).',
    requiredPermissions: Object.freeze([]),
    configSchema: Object.freeze({
      title: 'PermissionsScopeConfig',
      type: 'object',
      properties: {},
    }),
    dependencies: Object.freeze([]),
    tenantConfigKeys: Object.freeze(['permissions.scope']),
    status: 'active',
  }),
  'insurance-ga-excel': Object.freeze({
    featureId: 'insurance-ga-excel',
    label: 'GA 데이터',
    category: 'insurance',
    moduleType: 'detailTab',
    domains: Object.freeze(['insurance']),
    description: 'GA 엑셀 연동 패널.',
    requiredPermissions: Object.freeze([]),
    configSchema: Object.freeze({
      title: 'InsuranceGaExcelConfig',
      type: 'object',
      properties: {},
    }),
    routeBinding: {
      pathPattern: '/customers/:customerId/ga-excel',
      routeName: 'customer-ga-excel',
    },
    dependencies: Object.freeze([]),
    tenantConfigKeys: Object.freeze(['feature.insuranceGaExcel']),
    status: 'active',
  }),
  'insurance-auto-form': Object.freeze({
    featureId: 'insurance-auto-form',
    label: '자동차 신청',
    category: 'insurance',
    moduleType: 'detailTab',
    domains: Object.freeze(['insurance']),
    description: '자동차 신청 폼 패널.',
    requiredPermissions: Object.freeze([]),
    configSchema: Object.freeze({
      title: 'InsuranceAutoFormConfig',
      type: 'object',
      properties: {},
    }),
    dependencies: Object.freeze([]),
    tenantConfigKeys: Object.freeze(['feature.insuranceAutoForm']),
    status: 'active',
  }),
  'insurance-claim-requests': Object.freeze({
    featureId: 'insurance-claim-requests',
    label: '청구 요청',
    category: 'insurance',
    moduleType: 'detailTab',
    domains: Object.freeze(['insurance']),
    description: '보험 청구 요청 리스트/생성 패널.',
    requiredPermissions: Object.freeze([]),
    configSchema: Object.freeze({
      title: 'InsuranceClaimRequestsConfig',
      type: 'object',
      properties: {},
    }),
    dependencies: Object.freeze([]),
    tenantConfigKeys: Object.freeze(['feature.insuranceClaimRequests']),
    status: 'active',
  }),
  'insurance-cars': Object.freeze({
    featureId: 'insurance-cars',
    label: '차량',
    category: 'insurance',
    moduleType: 'detailTab',
    domains: Object.freeze(['insurance']),
    description: '다중 차량 관리 패널.',
    requiredPermissions: Object.freeze([]),
    configSchema: Object.freeze({
      title: 'InsuranceCarsConfig',
      type: 'object',
      properties: {},
    }),
    dependencies: Object.freeze([]),
    tenantConfigKeys: Object.freeze(['feature.insuranceCars']),
    status: 'active',
  }),
  'insurance-forms': Object.freeze({
    featureId: 'insurance-forms',
    label: '보험 양식',
    category: 'insurance',
    moduleType: 'panel',
    domains: Object.freeze(['insurance']),
    description: '보험 업무 양식·PDF 등.',
    requiredPermissions: Object.freeze([]),
    configSchema: Object.freeze({
      title: 'InsuranceFormsConfig',
      type: 'object',
      properties: {},
    }),
    dependencies: Object.freeze([]),
    tenantConfigKeys: Object.freeze(['feature.insuranceForms']),
    status: 'active',
  }),
  'insurer-manager-portal': Object.freeze({
    featureId: 'insurer-manager-portal',
    label: '보험사 관리자 포털',
    category: 'insurance',
    moduleType: 'integration',
    domains: Object.freeze(['insurance']),
    description: '보험사 설계사 전용 뉴스/포털 연계.',
    requiredPermissions: Object.freeze([]),
    configSchema: Object.freeze({
      title: 'InsurerManagerPortalConfig',
      type: 'object',
      properties: {},
    }),
    dependencies: Object.freeze([]),
    tenantConfigKeys: Object.freeze(['integrations.insurerManagerPortal']),
    status: 'active',
  }),
  'loss-adjuster-portal': Object.freeze({
    featureId: 'loss-adjuster-portal',
    label: '손해사정사 포털',
    category: 'insurance',
    moduleType: 'integration',
    domains: Object.freeze(['insurance']),
    description: '손해사정사 전용 포털 연계.',
    requiredPermissions: Object.freeze([]),
    configSchema: Object.freeze({
      title: 'LossAdjusterPortalConfig',
      type: 'object',
      properties: {},
    }),
    dependencies: Object.freeze([]),
    tenantConfigKeys: Object.freeze(['integrations.lossAdjusterPortal']),
    status: 'active',
  }),
  'workout-automation': Object.freeze({
    featureId: 'workout-automation',
    label: '운동 자동화',
    category: 'industry-extension',
    moduleType: 'backgroundJob',
    domains: Object.freeze(['gym']),
    description: '운동 루틴·기록 자동화(후보).',
    requiredPermissions: Object.freeze([]),
    configSchema: Object.freeze({
      title: 'WorkoutAutomationConfig',
      type: 'object',
      properties: {},
    }),
    dependencies: Object.freeze([]),
    tenantConfigKeys: Object.freeze(['gym.workoutAutomation']),
    status: 'preview',
  }),
  'membership-expiry-alert': Object.freeze({
    featureId: 'membership-expiry-alert',
    label: '회원권 만료 알림',
    category: 'industry-extension',
    moduleType: 'backgroundJob',
    domains: Object.freeze(['gym']),
    description: '만료 임박 알림 워크플로(후보).',
    requiredPermissions: Object.freeze([]),
    configSchema: Object.freeze({
      title: 'MembershipExpiryAlertConfig',
      type: 'object',
      properties: {},
    }),
    dependencies: Object.freeze([]),
    tenantConfigKeys: Object.freeze(['gym.membershipAlerts']),
    status: 'preview',
  }),
  'alcohol-order-management': Object.freeze({
    featureId: 'alcohol-order-management',
    label: '주류 발주 관리',
    category: 'industry-extension',
    moduleType: 'integration',
    domains: Object.freeze(['alcohol']),
    description: '도매 발주 프로세스(후보).',
    requiredPermissions: Object.freeze([]),
    configSchema: Object.freeze({
      title: 'AlcoholOrderMgmtConfig',
      type: 'object',
      properties: {},
    }),
    dependencies: Object.freeze([]),
    tenantConfigKeys: Object.freeze(['alcohol.orders']),
    status: 'preview',
  }),
  'gov-application-workflow': Object.freeze({
    featureId: 'gov-application-workflow',
    label: '정부 지원 신청 워크플로',
    category: 'industry-extension',
    moduleType: 'integration',
    domains: Object.freeze(['gov_support']),
    description: '지원 신청 단계별 워크플로(후보).',
    requiredPermissions: Object.freeze([]),
    configSchema: Object.freeze({
      title: 'GovApplicationWorkflowConfig',
      type: 'object',
      properties: {},
    }),
    dependencies: Object.freeze([]),
    tenantConfigKeys: Object.freeze(['gov.applicationWorkflow']),
    status: 'preview',
  }),
})
