import type { ListColumnRegistryEntry } from './customerTemplateRegistry.types'

/** columnKey(SSOT for listColumns[].columnKey) → 정의 */
export const LIST_COLUMN_REGISTRY_BY_KEY: Readonly<
  Record<string, Readonly<ListColumnRegistryEntry>>
> = Object.freeze({
  name: Object.freeze({
    columnKey: 'name',
    label: '이름',
    category: 'core',
    domains: Object.freeze(['core']),
    sourceType: 'field',
    sourceFieldKey: 'customer.name',
    valueType: 'string',
    privacyLevel: 'normal',
    sortable: true,
    filterable: true,
    visibleDefault: true,
    description: '표시 이름(고객 name 컬럼).',
    status: 'active',
  }),
  phone: Object.freeze({
    columnKey: 'phone',
    label: '연락처',
    category: 'contact',
    domains: Object.freeze(['core']),
    sourceType: 'field',
    sourceFieldKey: 'customer.phone',
    valueType: 'string',
    privacyLevel: 'normal',
    sortable: false,
    filterable: true,
    visibleDefault: true,
    description: '대표 전화번호.',
    status: 'active',
  }),
  isFavorite: Object.freeze({
    columnKey: 'isFavorite',
    label: '즐겨찾기',
    category: 'core',
    domains: Object.freeze(['core']),
    sourceType: 'field',
    sourceFieldKey: 'customer.isFavorite',
    valueType: 'boolean',
    privacyLevel: 'normal',
    sortable: true,
    filterable: true,
    visibleDefault: true,
    description: '중요/즐겨찾기 플래그.',
    status: 'active',
  }),
  createdAt: Object.freeze({
    columnKey: 'createdAt',
    label: '등록일',
    category: 'core',
    domains: Object.freeze(['core']),
    sourceType: 'field',
    sourceFieldKey: 'customer.createdAt',
    valueType: 'date',
    privacyLevel: 'normal',
    sortable: true,
    filterable: false,
    visibleDefault: true,
    description: '고객 레코드 생성 시각 컬럼.',
    status: 'active',
  }),
  assigneeUserId: Object.freeze({
    columnKey: 'assigneeUserId',
    label: '담당자',
    category: 'core',
    domains: Object.freeze(['core']),
    sourceType: 'field',
    sourceFieldKey: 'customer.assigneeUserId',
    valueType: 'number',
    privacyLevel: 'normal',
    sortable: true,
    filterable: true,
    visibleDefault: false,
    description: '담당 사용자 id 표시 컬럼.',
    status: 'active',
  }),
  memoSummary: Object.freeze({
    columnKey: 'memoSummary',
    label: '메모 요약',
    category: 'document',
    domains: Object.freeze(['core']),
    sourceType: 'derived',
    sourceFieldKey: 'customer.memo',
    valueType: 'string',
    privacyLevel: 'normal',
    sortable: false,
    filterable: false,
    visibleDefault: true,
    description: '인라인/노트에서 요약 문자열 파생 표시.',
    status: 'active',
  }),
  lastConsultDate: Object.freeze({
    columnKey: 'lastConsultDate',
    label: '최근 상담일',
    category: 'core',
    domains: Object.freeze(['core']),
    sourceType: 'aggregate',
    featureDependency: 'crm-consultations',
    valueType: 'date',
    privacyLevel: 'normal',
    sortable: true,
    filterable: false,
    visibleDefault: true,
    description: '상담 기능에서 집계한 최종 상담일.',
    status: 'active',
  }),
  ssnMasked: Object.freeze({
    columnKey: 'ssnMasked',
    label: '주민등록번호(표시)',
    category: 'personal',
    domains: Object.freeze(['insurance']),
    sourceType: 'derived',
    sourceFieldKey: 'insurance.ssn',
    valueType: 'string',
    privacyLevel: 'identifying',
    sortable: false,
    filterable: false,
    visibleDefault: true,
    description: 'SSN 마스킹 문자열 표시.',
    status: 'active',
  }),
  carNumber: Object.freeze({
    columnKey: 'carNumber',
    label: '차량번호',
    category: 'vehicle',
    domains: Object.freeze(['insurance']),
    sourceType: 'field',
    sourceFieldKey: 'vehicle.carNumber',
    valueType: 'string',
    privacyLevel: 'normal',
    sortable: false,
    filterable: true,
    visibleDefault: true,
    description: '대표 차량 번호판 표시 컬럼.',
    status: 'active',
  }),
  renewalDate: Object.freeze({
    columnKey: 'renewalDate',
    label: '만기일',
    category: 'insurance',
    domains: Object.freeze(['insurance']),
    sourceType: 'field',
    sourceFieldKey: 'insurance.renewalDate',
    valueType: 'date',
    privacyLevel: 'normal',
    sortable: true,
    filterable: false,
    visibleDefault: true,
    description: '갱신·만기 예정일.',
    status: 'active',
  }),
  insuranceAge: Object.freeze({
    columnKey: 'insuranceAge',
    label: '보험나이',
    category: 'insurance',
    domains: Object.freeze(['insurance']),
    sourceType: 'field',
    sourceFieldKey: 'insurance.insuranceAge',
    valueType: 'number',
    privacyLevel: 'normal',
    sortable: true,
    filterable: false,
    visibleDefault: false,
    description: '보험나이 표시 컬럼.',
    status: 'active',
  }),
  nextAgeDate: Object.freeze({
    columnKey: 'nextAgeDate',
    label: '상령일',
    category: 'insurance',
    domains: Object.freeze(['insurance']),
    sourceType: 'field',
    sourceFieldKey: 'insurance.nextAgeDate',
    valueType: 'date',
    privacyLevel: 'normal',
    sortable: true,
    filterable: false,
    visibleDefault: false,
    description: '상령일 표시 컬럼.',
    status: 'active',
  }),
})
