import crypto from 'node:crypto'
import { findPromotionCodeByNormalized } from './promotionService.js'
import { normalizePromotionCode } from './promotionCode.js'

export const PROMOTION_CODE_AUTO_ALPHABET = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'
export const PROMOTION_CODE_AUTO_LENGTH = 5
export const PROMOTION_CODE_GENERATE_MAX_ATTEMPTS = 50

/**
 * @param {number} [length]
 */
export function generateCandidatePromotionCode(length = PROMOTION_CODE_AUTO_LENGTH) {
  let code = ''
  for (let index = 0; index < length; index += 1) {
    const randomIndex = crypto.randomInt(0, PROMOTION_CODE_AUTO_ALPHABET.length)
    code += PROMOTION_CODE_AUTO_ALPHABET[randomIndex]
  }
  return code
}

/**
 * @param {string} code
 */
export function isValidAutoGeneratedPromotionCode(code) {
  if (String(code).length !== PROMOTION_CODE_AUTO_LENGTH) return false
  for (const ch of String(code)) {
    if (!PROMOTION_CODE_AUTO_ALPHABET.includes(ch)) return false
  }
  return true
}

/**
 * @param {import('pg').Pool} pool
 * @returns {Promise<{ code: string }>}
 */
export async function generateUniquePromotionCodeAdmin(pool) {
  for (let attempt = 0; attempt < PROMOTION_CODE_GENERATE_MAX_ATTEMPTS; attempt += 1) {
    const code = generateCandidatePromotionCode()
    const normalized = normalizePromotionCode(code)
    const existing = await findPromotionCodeByNormalized(pool, normalized)
    if (!existing) {
      return { code: normalized }
    }
  }
  throw new Error('promotion_code_generate_failed')
}
