import assert from 'node:assert/strict'
import crypto from 'node:crypto'
import test from 'node:test'
import { summarizeLegacyReferralBenefit, summarizePromotionBenefit } from './promotionBenefit.js'
import {
  generateCandidatePromotionCode,
  generateUniquePromotionCodeAdmin,
  isValidAutoGeneratedPromotionCode,
  PROMOTION_CODE_AUTO_ALPHABET,
  PROMOTION_CODE_AUTO_LENGTH,
  PROMOTION_CODE_GENERATE_MAX_ATTEMPTS,
} from './generatePromotionCode.js'
import { createPromotionCodeAdmin } from './promotionAdminService.js'
import { calculatePromotionDiscountForMonth } from './promotionService.js'
import { normalizePromotionCode } from './promotionCode.js'
import { validatePromotionOrReferralCode } from './validatePromotionOrReferral.js'

test('normalizePromotionCode trims and uppercases', () => {
  assert.equal(normalizePromotionCode(' promo-01 '), 'PROMO-01')
  assert.equal(normalizePromotionCode(''), '')
})

test('generateCandidatePromotionCode — 5 chars from allowed alphabet only', () => {
  const excluded = new Set(['O', '0', 'I', '1'])
  for (let index = 0; index < 200; index += 1) {
    const code = generateCandidatePromotionCode()
    assert.equal(code.length, PROMOTION_CODE_AUTO_LENGTH)
    assert.equal(code, code.toUpperCase())
    assert.ok(isValidAutoGeneratedPromotionCode(code))
    for (const ch of code) {
      assert.ok(PROMOTION_CODE_AUTO_ALPHABET.includes(ch))
      assert.ok(!excluded.has(ch))
    }
  }
})

test('generateUniquePromotionCodeAdmin — returns unused code', async () => {
  const pool = {
    query: async (sql, params) => {
      const text = String(sql)
      if (text.includes('promotion_codes') && text.includes('code_normalized')) {
        return { rowCount: 0, rows: [] }
      }
      return { rowCount: 0, rows: [] }
    },
  }
  const result = await generateUniquePromotionCodeAdmin(pool)
  assert.equal(result.code.length, PROMOTION_CODE_AUTO_LENGTH)
  assert.ok(isValidAutoGeneratedPromotionCode(result.code))
})

test('generateUniquePromotionCodeAdmin — retries until unique', async () => {
  const originalRandomInt = crypto.randomInt
  try {
    const sequences = [
      [0, 0, 0, 0, 0],
      [1, 1, 1, 1, 1],
    ]
    let sequenceIndex = 0
    let charIndex = 0
    crypto.randomInt = () => {
      const sequence = sequences[sequenceIndex] ?? sequences[sequences.length - 1]
      const value = sequence[charIndex]
      charIndex += 1
      if (charIndex >= PROMOTION_CODE_AUTO_LENGTH) {
        charIndex = 0
        sequenceIndex += 1
      }
      return value
    }
    const firstCode = PROMOTION_CODE_AUTO_ALPHABET[0].repeat(PROMOTION_CODE_AUTO_LENGTH)
    const secondCode = PROMOTION_CODE_AUTO_ALPHABET[1].repeat(PROMOTION_CODE_AUTO_LENGTH)
    const taken = new Set([firstCode])
    const pool = {
      query: async (sql, params) => {
        const text = String(sql)
        if (text.includes('promotion_codes') && text.includes('code_normalized') && taken.has(params?.[0])) {
          return {
            rowCount: 1,
            rows: [{ id: 1, code_normalized: params[0], code: params[0] }],
          }
        }
        return { rowCount: 0, rows: [] }
      },
    }
    const result = await generateUniquePromotionCodeAdmin(pool)
    assert.equal(result.code, secondCode)
  } finally {
    crypto.randomInt = originalRandomInt
  }
})

test('generateUniquePromotionCodeAdmin — fails after max attempts', async () => {
  const originalRandomInt = crypto.randomInt
  try {
    crypto.randomInt = () => 0
    const dupCode = PROMOTION_CODE_AUTO_ALPHABET[0].repeat(PROMOTION_CODE_AUTO_LENGTH)
    const pool = {
      query: async (sql, params) => {
        const text = String(sql)
        if (text.includes('promotion_codes') && text.includes('code_normalized') && params?.[0] === dupCode) {
          return {
            rowCount: 1,
            rows: [{ id: 1, code_normalized: dupCode, code: dupCode }],
          }
        }
        return { rowCount: 0, rows: [] }
      },
    }
    await assert.rejects(
      () => generateUniquePromotionCodeAdmin(pool),
      (error) => error instanceof Error && error.message === 'promotion_code_generate_failed',
    )
    assert.ok(PROMOTION_CODE_GENERATE_MAX_ATTEMPTS >= 20)
  } finally {
    crypto.randomInt = originalRandomInt
  }
})

test('createPromotionCodeAdmin — rejects duplicate code with 409 error key', async () => {
  const dupCode = 'DUP01'
  const pool = {
    query: async (sql, params) => {
      const text = String(sql)
      if (text.includes('promotion_codes') && text.includes('code_normalized') && text.includes('SELECT')) {
        return {
          rowCount: 1,
          rows: [{ id: 1, code_normalized: dupCode, code: dupCode }],
        }
      }
      throw new Error('unexpected_query')
    },
  }
  await assert.rejects(
    () =>
      createPromotionCodeAdmin(
        pool,
        {
          code: dupCode,
          codeType: 'discount',
          discountType: 'first_month_fixed',
          discountAmount: 2000,
          ownerType: 'normal',
        },
        'admin-user',
      ),
    (error) => error instanceof Error && error.message === 'promotion_code_duplicate',
  )
})

test('calculatePromotionDiscountForMonth — first_month_fixed', () => {
  const promo = {
    discountType: 'first_month_fixed',
    discountAmount: 3000,
    durationMonths: null,
  }
  const first = calculatePromotionDiscountForMonth(promo, { baseSupplyAmount: 8000, monthIndex: 1 })
  const second = calculatePromotionDiscountForMonth(promo, { baseSupplyAmount: 8000, monthIndex: 2 })
  assert.equal(first.promotionDiscountSupplyAmount, 3000)
  assert.equal(first.applicable, true)
  assert.equal(second.promotionDiscountSupplyAmount, 0)
  assert.equal(second.applicable, false)
})

test('calculatePromotionDiscountForMonth — first_month_free', () => {
  const promo = { discountType: 'first_month_free', discountAmount: null, durationMonths: null }
  const first = calculatePromotionDiscountForMonth(promo, { baseSupplyAmount: 8000, monthIndex: 1 })
  assert.equal(first.promotionDiscountSupplyAmount, 8000)
})

test('calculatePromotionDiscountForMonth — recurring_percent within duration', () => {
  const promo = {
    discountType: 'recurring_percent',
    discountPercent: 10,
    durationMonths: 3,
  }
  const m2 = calculatePromotionDiscountForMonth(promo, { baseSupplyAmount: 8000, monthIndex: 2 })
  const m4 = calculatePromotionDiscountForMonth(promo, { baseSupplyAmount: 8000, monthIndex: 4 })
  assert.equal(m2.promotionDiscountSupplyAmount, 800)
  assert.equal(m4.promotionDiscountSupplyAmount, 0)
})

test('calculatePromotionDiscountForMonth — caps discount at base supply', () => {
  const promo = { discountType: 'first_month_fixed', discountAmount: 12000, durationMonths: null }
  const first = calculatePromotionDiscountForMonth(promo, { baseSupplyAmount: 8000, monthIndex: 1 })
  assert.equal(first.promotionDiscountSupplyAmount, 8000)
})

test('summarizePromotionBenefit — legacy referral uses policy amount', () => {
  const legacy = summarizeLegacyReferralBenefit()
  assert.match(legacy, /첫 달/)
  assert.match(legacy, /2,000원\(공급가\)/)
})

test('summarizePromotionBenefit — first month percent', () => {
  const promo = {
    discountType: 'first_month_percent',
    discountPercent: 50,
    discountAmount: null,
    durationMonths: null,
  }
  const text = summarizePromotionBenefit(promo, 8000)
  assert.match(text, /50%/)
  assert.match(text, /4,000원/)
})

test('validatePromotionOrReferralCode — not_found falls back to legacy referral', async () => {
  const legacyCode = 'LEGACY1'
  const executor = {
    query: async (sql, params) => {
      const text = String(sql)
      if (text.includes('promotion_codes') && text.includes('code_normalized')) {
        return { rowCount: 0, rows: [] }
      }
      if (text.includes('referral_codes') && params?.[0] === legacyCode) {
        return {
          rowCount: 1,
          rows: [{ owner_user_id: 'user-referrer', code: legacyCode }],
        }
      }
      if (text.includes('FROM users') && text.includes('status') && params?.[0] === 'user-referrer') {
        return { rowCount: 1, rows: [{ id: 'user-referrer', status: 'active' }] }
      }
      return { rowCount: 0, rows: [] }
    },
  }

  const result = await validatePromotionOrReferralCode(executor, legacyCode)
  assert.equal(result.ok, true)
  assert.equal(result.source, 'legacy_referral')
  assert.equal(result.legacy?.code, legacyCode)
})
