export const INTENT_DOMAIN = Object.freeze({
  GENERAL_CHAT: 'GENERAL_CHAT',
  CUSTOMER: 'CUSTOMER',
  ONE_FC_QUERY: 'ONE_FC_QUERY',
  ONE_FC_ACTION: 'ONE_FC_ACTION',
  UNSUPPORTED_ONE_FC_ACTION: 'UNSUPPORTED_ONE_FC_ACTION',
  CUSTOMER_IMPORT: 'CUSTOMER_IMPORT',
  CLARIFY: 'CLARIFY',
  /** @deprecated mapped to GENERAL_CHAT at runtime */
  OTHER: 'OTHER',
  /** @deprecated mapped to GENERAL_CHAT at runtime */
  UNKNOWN: 'UNKNOWN',
})

export const INTENT_STAGE = Object.freeze({
  ANSWER: 'ANSWER',
  ANALYZE: 'ANALYZE',
  PREVIEW: 'PREVIEW',
  MODIFY: 'MODIFY',
  COMMIT_REQUEST: 'COMMIT_REQUEST',
  QUERY: 'QUERY',
  CLARIFY: 'CLARIFY',
  WAIT: 'WAIT',
})

export const TOP_LEVEL_ACTION = Object.freeze({
  GENERAL_CHAT_ANSWER: 'GENERAL_CHAT_ANSWER',
  UNSUPPORTED_TOOL: 'UNSUPPORTED_TOOL',
  CLARIFY: 'CLARIFY',
  ROUTE_CUSTOMER_IMPORT: 'ROUTE_CUSTOMER_IMPORT',
})

export const IMPORT_ORCHESTRATION_ACTION = Object.freeze({
  START_IMPORT_ANALYSIS: 'START_IMPORT_ANALYSIS',
  RUN_PREVIEW_PIPELINE: 'RUN_PREVIEW_PIPELINE',
  WAIT_IMPORT_ANALYSIS: 'WAIT_IMPORT_ANALYSIS',
  COMMIT_BUTTON_GUIDANCE: 'COMMIT_BUTTON_GUIDANCE',
  MODIFY_DUPLICATE_POLICY: 'MODIFY_DUPLICATE_POLICY',
  MODIFY_MAPPING: 'MODIFY_MAPPING',
  CLARIFY: 'CLARIFY',
  IMPORT_SESSION_HELP: 'IMPORT_SESSION_HELP',
  UNCONNECTED_TOOL: 'UNCONNECTED_TOOL',
  UNSTRUCTURED_MAPPING_INFO: 'UNSTRUCTURED_MAPPING_INFO',
})
