export const INTENT_DOMAIN = Object.freeze({
  CUSTOMER_IMPORT: 'CUSTOMER_IMPORT',
  OTHER: 'OTHER',
  UNKNOWN: 'UNKNOWN',
})

export const INTENT_STAGE = Object.freeze({
  ANALYZE: 'ANALYZE',
  PREVIEW: 'PREVIEW',
  MODIFY: 'MODIFY',
  COMMIT_REQUEST: 'COMMIT_REQUEST',
  QUERY: 'QUERY',
  CLARIFY: 'CLARIFY',
  WAIT: 'WAIT',
})

export const IMPORT_ORCHESTRATION_ACTION = Object.freeze({
  START_IMPORT_ANALYSIS: 'START_IMPORT_ANALYSIS',
  RUN_PREVIEW_PIPELINE: 'RUN_PREVIEW_PIPELINE',
  WAIT_IMPORT_ANALYSIS: 'WAIT_IMPORT_ANALYSIS',
  COMMIT_BUTTON_GUIDANCE: 'COMMIT_BUTTON_GUIDANCE',
  MODIFY_DUPLICATE_POLICY: 'MODIFY_DUPLICATE_POLICY',
  MODIFY_MAPPING: 'MODIFY_MAPPING',
  CLARIFY: 'CLARIFY',
  IMPORT_SESSION_HELP: 'IMPORT_SESSION_HELP',
  UNCONNECTED_TOOL: 'UNCONNECTED_TOOL',
  UNSTRUCTURED_MAPPING_INFO: 'UNSTRUCTURED_MAPPING_INFO',
})
